# -*- coding: utf-8 -*-
"""All researched data for Master Industry Database.xlsx.

CONVENTIONS
  FY2026 = 1 April 2025 to 31 March 2026.
  NA sentinel is the string in style.NA, rendered as "Data Not Publicly Available".
  Fiscal-year matrices run FY2022..FY2026 left to right so a new year is a single
  appended column; no formula in the workbook is hard-wired to a column count.
  Rs crore = Rs 10 million. Mt = million tonnes.
"""
from .style import NA

CUTOFF = "03-Aug-2026"
FY_COLS = ["FY2022", "FY2023", "FY2024", "FY2025", "FY2026"]

# Marker for figures that exist but were not verified in this research cycle.
NV = "Not verified in this cycle"

# ======================================================================================
# 1. COMPANY LIST
# ======================================================================================
COMPANY_HEADERS = [
    "#", "Company (legal name)", "Short Name", "Coverage Tier", "NSE Symbol",
    "Listing Status", "Controlling Shareholder / Promoter Group",
    "Primary Steelmaking Route", "Principal Assets / Locations", "Product Focus",
    "Consolidation Basis Used In This Workbook", "Fiscal Year End", "Reporting Currency",
    "Latest Reported Period At Cutoff", "Asset Detail Verification", "Source ID",
    "Confidence", "Notes",
]

COMPANIES = [
    (1, "Tata Steel Limited", "Tata Steel", "Core", "TATASTEEL", "Listed - NSE and BSE",
     "Tata Sons Private Limited (Tata Group)",
     "BF-BOF in India and Netherlands; BF-BOF and EAF in UK; scrap-based EAF at Ludhiana",
     "India: Jamshedpur (Jharkhand), Kalinganagar and Meramandali (Odisha), NINL, Ludhiana EAF (Punjab). Europe: IJmuiden (Netherlands), Port Talbot (UK)",
     "Flat products, long products, tubes, tinplate, wires, branded retail (Tata Tiscon)",
     "Consolidated, Ind-AS", "31-Mar", "INR",
     "FY2026 audited (15-May-2026); Q1FY2027 reported 31-Jul-2026",
     "Verified from FY2026 primary disclosure", "S08, S37", "High",
     "Group crude steel capacity 35 Mtpa. 0.75 Mtpa Ludhiana EAF commissioned Mar-2026. Netherlands carries a disclosed material uncertainty related to going concern - see Government Policies sheet."),

    (2, "JSW Steel Limited", "JSW Steel", "Core", "JSWSTEEL", "Listed - NSE and BSE",
     "JSW Group (Sajjan Jindal family)",
     "BF-BOF and DRI-EAF",
     "India: Vijayanagar (Karnataka), Dolvi (Maharashtra), Salem (Tamil Nadu), JVML Vijayanagar. Overseas: Ohio (USA), Italy",
     "Flat products, long products, coated products, special steel",
     "Consolidated, Ind-AS", "31-Mar", "INR", "FY2026 (results 14-May-2026)",
     "Verified from FY2026 primary disclosure", "S09", "High",
     "BPSL steel business transferred to the JSW JFE joint venture and deconsolidated with effect from 27-Mar-2026, which materially changes the FY2026 to FY2027 comparability of volumes, revenue and net debt."),

    (3, "Steel Authority of India Limited", "SAIL", "Core", "SAIL", "Listed - NSE and BSE",
     "President of India / Government of India (majority shareholder)",
     "BF-BOF",
     "Bhilai (Chhattisgarh), Durgapur and IISCO Burnpur and Alloy Steels Plant (West Bengal), Rourkela (Odisha), Bokaro (Jharkhand), Salem Steel Plant (Tamil Nadu)",
     "Long products, plates, HR and CR coil, rails, alloy and stainless steel",
     "Consolidated, Ind-AS (note: company's headline EBITDA is standalone)", "31-Mar", "INR",
     "FY2026 audited (15-May-2026)", "Verified from FY2026 primary disclosure",
     "S10, S26", "High",
     "Operating capacity 19.676 Mtpa across seven plants per Ministry of Steel. Board-approved expansions total 7.62 Mtpa. See Conflict C09 on the standalone versus consolidated EBITDA basis."),

    (4, "Jindal Steel Limited (formerly Jindal Steel & Power Limited)", "Jindal Steel",
     "Core", "JINDALSTEL", "Listed - NSE and BSE",
     "O. P. Jindal Group (Naveen Jindal family)",
     "DRI-EAF and BF-BOF, with captive iron ore, thermal coal and coking coal",
     "Angul (Odisha), Raigarh (Chhattisgarh), Patratu (Jharkhand); pellet capacity at Barbil (Odisha)",
     "Plates and coils, rails, structurals, TMT bars, parallel flange beams",
     "Consolidated, Ind-AS", "31-Mar", "INR",
     "FY2026 (results 01-May-2026); Q1FY2027 reported 24-Jul-2026",
     "Verified from FY2026 primary disclosure", "S11, S41", "High",
     "Angul expanded from 6.0 to 12.0 Mtpa during FY2026, taking group steelmaking capacity from 9.6 to 15.6 Mtpa entering FY2027. See Conflict C02 on the revenue basis."),

    (5, "ArcelorMittal Nippon Steel India Limited", "AM/NS India", "Core", "Unlisted",
     "Unlisted - 60:40 joint venture; no listed equity",
     "ArcelorMittal S.A. 60% / Nippon Steel Corporation 40%",
     "BF-BOF and gas-based DRI-EAF at Hazira",
     "Hazira (Gujarat) integrated works; announced greenfield integrated plant at Rajayyapeta (Andhra Pradesh), Phase 1 of 8.2 Mtpa",
     "Flat products - hot rolled, cold rolled, coated - and plates",
     "100% basis as disclosed by ArcelorMittal S.A., in USD, on CALENDAR quarters",
     "31-Dec (as disclosed by parent)", "USD", "2Q CY2026 (Apr-Jun 2026)",
     "Verified from FY2026 primary disclosure (parent)", "S13, S14, S15", "High",
     "Does not publish full Ind-AS consolidated statements publicly. Fiscal-year figures in this workbook are DERIVED by summing calendar quarters - see Conflict C16. Hazira expanding from 9 to 15 Mtpa; potential further expansion to 24 Mtpa under study; stated long-term pathway to 40 Mt in India."),

    (6, "Jindal Stainless Limited", "Jindal Stainless", "Core", "JSL", "Listed - NSE and BSE",
     "Jindal Stainless promoter group (Ratan Jindal family)",
     "EAF with AOD converter - stainless steel melting",
     "Jajpur (Odisha), Hisar (Haryana); cold rolling at Hisar and Kharagpur; stainless melt shop in Indonesia",
     "Stainless steel flat products - 200, 300 and 400 series",
     "Consolidated, Ind-AS", "31-Mar", "INR", "FY2026 (results and call early-May-2026)",
     "Verified from FY2026 primary disclosure", "S12", "High",
     "Total melt capacity 4.2 Mtpa comprising 3.0 Mtpa in India and 1.2 Mtpa in Indonesia, the latter commissioned ahead of schedule in FY2026. Sales volume target of 3.5 Mtpa by FY2029."),

    (7, "Rashtriya Ispat Nigam Limited", "RINL", "Core", "Unlisted",
     "Unlisted - 100% Government of India",
     "Government of India", "BF-BOF",
     "Visakhapatnam Steel Plant (Andhra Pradesh)",
     "Long products - bars, rounds, wire rod, structurals, forged products",
     "Not applicable - audited statutory financials not publicly available for FY2026",
     "31-Mar", "INR", "FY2026 operating and turnover data only (01-Apr-2026 release)",
     "Operating data verified; capacity indicative", "S16, S01", "Medium",
     "Returned to monthly cash profit in Jan-2026 (Rs 54 cr) after sustained Government support. Volumes rose ~51% in FY2026 off a very low FY2025 base. Nameplate liquid steel capacity of 7.3 Mtpa is widely cited but was NOT verified within this research cycle."),

    (8, "Shyam Metalics and Energy Limited", "Shyam Metalics", "Supporting", "SHYAMMETL",
     "Listed - NSE and BSE", "Promoter group (Agarwal family)",
     "DRI plus induction and electric arc furnace, with captive power and ferro alloys",
     "Integrated facilities in West Bengal (including Jamuria) and Odisha; captive power ~357 MW",
     "Long products, billets, sponge iron, pellets, ferro alloys, aluminium foil, cold rolled products",
     "Consolidated, Ind-AS", "31-Mar", "INR", "FY2026 audited (board 11-May-2026)",
     "Indicative - verify against annual report", "S31, S38, S39", "Medium",
     "CRITICAL DEFINITION: the company's 'aggregate installed metal capacity' of 15.13 Mtpa (31-Dec-2024) spans intermediate AND final products and therefore double-counts within the value chain. It is NOT crude steel capacity. Announced ~USD 1.1bn expansion to ~27 Mtpa by FY2031. Reported EBITDA includes other income - see Conflict C10."),

    (9, "Godawari Power & Ispat Limited", "Godawari Power", "Supporting", "GPIL",
     "Listed - NSE and BSE", "Promoter group (Agrawal family)",
     "DRI-EAF, integrated backwards into captive iron ore and pellets",
     "Siltara and Raipur (Chhattisgarh), with captive iron ore mining",
     "Sponge iron, billets, wire rod, HB wire, iron ore pellets, ferro alloys",
     "Consolidated, Ind-AS", "31-Mar", "INR", "FY2026", "Indicative - verify against annual report",
     "S30", "Medium",
     "Highest operating margin in the supporting set (FY2026 standardised margin ~23%), reflecting captive iron ore. Volumes not disclosed in the sources available, so EBITDA per tonne is not computed."),

    (10, "APL Apollo Tubes Limited", "APL Apollo", "Supporting", "APLAPOLLO",
     "Listed - NSE and BSE", "Promoter group (Sanjay Gupta family)",
     "NOT a steelmaker - electric resistance welded structural steel tube converter; a buyer of hot rolled coil",
     "Multiple ERW tube and hollow-section plants across India",
     "Structural steel tubes and hollow sections, pre-galvanised and colour-coated tubes",
     "Consolidated, Ind-AS", "31-Mar", "INR", "FY2026", "Indicative - verify against annual report",
     "S30", "Medium",
     "ANALYTICAL WARNING: a downstream converter, not a crude steel producer. Its input is HRC, so it is a beneficiary of falling steel prices and is inversely exposed to the safeguard duty relative to the integrated mills. EXCLUDE from crude steel capacity, crude steel volume and EBITDA-per-tonne-of-crude-steel comparisons."),

    (11, "Mukand Limited", "Mukand", "Supporting", "MUKANDLTD", "Listed - NSE and BSE",
     "Bajaj group and Mukand promoter group",
     "EAF - alloy and specialty steel long products",
     "Ginigera (Karnataka) and Thane / Kalwe (Maharashtra)",
     "Alloy and stainless steel bars and wire rods; industrial machinery and cranes",
     "Consolidated, Ind-AS", "31-Mar", "INR", "FY2026", "Indicative - verify against annual report",
     "S30", "Medium",
     "FY2026 net profit of Rs 604 cr materially exceeds standardised EBITDA of Rs 172 cr, indicating a large non-operating or exceptional item. Do NOT use FY2026 Mukand earnings in operating comparisons - see Conflict C11."),

    (12, "Gallantt Ispat Limited", "Gallantt", "Supporting", "GALLANTT",
     "Listed - NSE and BSE", "Gallantt promoter group",
     "Integrated DRI and induction furnace with rolling mills and captive power",
     "Gorakhpur (Uttar Pradesh) and Gujarat",
     "TMT bars, billets, sponge iron; also an agri-products (flour) business",
     "Consolidated, Ind-AS", "31-Mar", "INR", "FY2026", "Indicative - verify against annual report",
     "S30", "Medium",
     "Gallantt Metal was amalgamated into Gallantt Ispat, so pre-merger periods are not like-for-like. FY2026 annual revenue column differs from the sum of quarters by Rs 19 cr - see Conflict C13."),

    (13, "Uttam Galva Steels Limited", "Uttam Galva", "Supporting", "Delisted",
     "Delisted - trading suspended 17-Oct-2022; delisted 08-Dec-2022",
     "AM Mining India Private Limited (ArcelorMittal group), following the NCLT-approved resolution plan",
     "NOT a steelmaker - cold rolling and galvanising converter",
     "Khopoli (Maharashtra)",
     "Cold rolled coil, galvanised plain and corrugated (GP/GC) products",
     "Not applicable - no public financial statements from FY2023 onwards",
     "31-Mar", "INR", "FY2022 (last publicly available annual period)",
     "Status verified from insolvency and exchange records", "S36", "High",
     "Resolved under the Insolvency and Bankruptcy Code. NCLT Mumbai approved AM Mining India's resolution plan by order delivered 14-Oct-2022; the acquisition completed in Nov-2022. The company now sits inside the ArcelorMittal ownership chain, so it is no longer an independent listed comparable. Retained in the universe for continuity of mandated coverage."),

    (14, "Electrosteel Steels Limited (now ESL Steel Limited)", "Electrosteel / ESL",
     "Supporting", "Delisted", "Delisted - resolved under the IBC; equity delisted",
     "Vedanta Limited (steel business placed in Vedanta Iron & Steel on demerger effective 01-May-2026)",
     "BF-BOF - greenfield integrated plant",
     "Siyaljori, Chandankyari, Bokaro district (Jharkhand)",
     "Pig iron, billets, TMT bars, wire rods, ductile iron pipes",
     "Not applicable - FY2025 and FY2026 statutory financials not publicly available",
     "31-Mar", "INR", "FY2024 (last annual report located)",
     "Status and capacity verified from company and parent sources", "S35, S34, S43", "Medium",
     "Commissioned capacity 1.5 Mtpa. Vedanta targeting a doubling of Bokaro steelmaking capacity to 3.0 Mtpa by end-CY2026 (single secondary source - indicative). Vedanta's Q4/FY26 press release does NOT disclose a separate ESL revenue, EBITDA or steel production line item, so no FY2026 financials can be sourced."),

    (15, "Kirloskar Ferrous Industries Limited", "Kirloskar Ferrous", "Supporting", "KIRLFER",
     "Listed - NSE and BSE", "Kirloskar group",
     "Mini blast furnace pig iron and iron castings; alloy steel and seamless tubes through subsidiary ISMT",
     "Koppal (Karnataka) and Solapur (Maharashtra); ISMT facilities at Ahmednagar and Baramati",
     "Pig iron, iron castings, alloy steel, seamless tubes",
     "Consolidated, Ind-AS", "31-Mar", "INR", "FY2026", "Indicative - verify against annual report",
     "S30", "Medium",
     "Predominantly a pig iron, castings and tubes producer rather than a crude steel producer. FY2026 net profit of Rs 507 cr exceeds profit before tax of Rs 497 cr, indicating a net tax credit - see Conflict C12."),
]

# ======================================================================================
# 2. PRODUCTION CAPACITY
# ======================================================================================
CAPACITY_INDUSTRY_HEADERS = [
    "Metric", "Unit", "FY2024", "FY2025", "FY2026", "FY2031 Target",
    "Period Type", "Source ID", "Methodology", "Confidence", "Notes",
]

CAPACITY_INDUSTRY = [
    ("India crude steel capacity", "Mtpa", 179.51, 200.33, 220.4, 300.0,
     "Annual (FY), year-end", "S02, S03", "As reported", "High",
     "JPC data as published by the Ministry of Steel. FY2031 target of 300 Mtpa is the National Steel Policy 2017 aspiration. The Mar-2026 Ministry vintage stated 220.3 Mt - see Conflict C04."),
    ("Implied capacity utilisation (crude steel)", "%", 0.8039, 0.7596, 0.7642, None,
     "Annual (FY)", "S01, S02", "Computed: crude steel production divided by year-end capacity",
     "High",
     "Computed in-cell. Uses year-end capacity as the denominator, so it understates true utilisation in years of heavy capacity commissioning. FY2024 144.30/179.51; FY2025 152.18/200.33; FY2026 168.42/220.4."),
    ("Capacity added during the year", "Mtpa", None, 20.82, 20.07, None,
     "Annual (FY)", "S02", "Computed: year-on-year change in capacity", "High",
     "India added roughly 20 Mtpa in each of FY2025 and FY2026 - the fastest sustained capacity build of any steel industry globally over the period."),
]

CAPACITY_COMPANY_HEADERS = [
    "Company", "Coverage Tier", "Capacity Definition", "Unit",
    "Capacity At FY2026 Year-End", "Announced / Approved Growth Pipeline",
    "Indicative Capacity On Completion", "Approval Status Of Pipeline",
    "Target Date", "Source ID", "Methodology", "Confidence", "Notes",
]

CAPACITY_COMPANY = [
    ("Tata Steel", "Core", "Crude steel capacity, global group", "Mtpa", 35.0, NA, 40.0,
     "Announced - India roadmap", "Not specified", "S08, S37", "As reported", "High",
     "Group crude steel capacity of 35 Mtpa stated in the FY2026 results release. The 40 Mtpa figure is the India expansion roadmap presented with Q1FY2027 results (31-Jul-2026) and is an ambition, not a Board-approved tranche. 0.75 Mtpa scrap-based EAF at Ludhiana commissioned Mar-2026; a 4.8 Mtpa expansion at NINL is proposed."),
    ("JSW Steel", "Core", "Crude steel capacity, India - JSW Steel entity, existing", "Mtpa",
     31.9, 4.5, 36.4, "Under implementation", "Not specified", "S09",
     "As reported; cross-checked", "High",
     "Cross-check: FY2026 India production of 29.25 Mt at the stated 92% utilisation implies ~31.8 Mtpa, consistent with 31.9 Mtpa. Vijayanagar BF-3 expansion from 3.0 to 4.5 Mtpa was under testing and commissioning and is excluded from the utilisation calculation."),
    ("JSW Steel", "Core", "Crude steel capacity, India - including joint ventures, as presented",
     "Mtpa", 62.0, 16.0, 78.0, "Mixed - existing plus Board-approved plus announced",
     "Various to 2031", "S09", "As reported", "Medium",
     "The company presents India capacity of 62.0 Mtpa existing plus a 16.0 Mtpa growth pipeline, totalling 78.0 Mtpa, versus 34.2 plus 15.8 equals 50.0 Mtpa as at Mar-2025. The step-up reflects the inclusion of joint ventures. The split between the JSW Steel entity and the JVs was presented graphically and could not be extracted unambiguously, so Confidence is Medium on the split, High on the 62.0 / 16.0 / 78.0 totals. Includes the announced 50:50 POSCO JV (6 Mtpa greenfield in Odisha by 2031), the JSW JFE JV, BMM Ispat (0.9 Mtpa) and a 5 Mtpa brownfield expansion at JVML-Vijayanagar."),
    ("SAIL", "Core", "Crude steel operating capacity", "Mtpa", 19.676, 7.62, 27.296,
     "Board approved", "Not specified", "S26", "As reported", "High",
     "Plant-wise per Ministry of Steel: Bhilai 6.16, Bokaro 4.6, Rourkela 3.8, IISCO 2.5, Durgapur 2.2, Alloy Steels Plant 0.234, Salem 0.18. Board-approved additions: IISCO greenfield 4.08 Mtpa, Bokaro brownfield 2.65 Mtpa, Durgapur brownfield 0.89 Mtpa. A ~35 Mt ambition by FY2031 at roughly Rs 1 lakh crore has been stated publicly but is not a Board-approved tranche."),
    ("Jindal Steel", "Core", "Crude steel capacity", "Mtpa", 15.6, NA, NA,
     "Commissioned", "Achieved in FY2026", "S11", "As reported", "High",
     "Capacity rose from 9.6 to 15.6 Mtpa during FY2026, principally the Angul expansion from 6.0 to 12.0 Mtpa. Iron-making capacity is being increased by 6.6 Mtpa, with elements still under construction."),
    ("AM/NS India", "Core", "Crude steel capacity, Hazira", "Mtpa", 9.0, 6.0, 15.0,
     "Under implementation", "Not specified", "S13, S14", "As reported", "High",
     "Hazira expanding from 9 to 15 Mtpa. Detailed engineering under way for a potential further expansion of Hazira to 24 Mtpa. Stated long-term pathway to 40 Mt of Indian steelmaking capacity. Separately, a greenfield integrated plant at Rajayyapeta, Andhra Pradesh with Phase 1 capacity of 8.2 Mtpa was announced on 23-Mar-2026."),
    ("Jindal Stainless", "Core", "Stainless steel melt capacity, total group", "Mtpa", 4.2, NA, NA,
     "Commissioned", "Achieved in FY2026", "S12", "As reported", "High",
     "Comprises 3.0 Mtpa in India and 1.2 Mtpa in Indonesia, the Indonesian stainless melt shop having been commissioned ahead of schedule in FY2026. Downstream: 1.1 Mtpa HRAP and 0.17 Mtpa CRAP lines at Jajpur upcoming; a further Rs 900 cr committed to cold rolling at Hisar and Kharagpur taking CRAP capacity to 2.67 Mtpa by FY2028."),
    ("RINL", "Core", "Liquid steel capacity, Visakhapatnam Steel Plant", "Mtpa", NA, NA, NA,
     NA, NA, "S16", "Not sourced", "Low",
     "A nameplate liquid steel capacity of 7.3 Mtpa is widely cited but was NOT verified from a primary source within this research cycle and is therefore not asserted. FY2026 liquid steel output of 5.694 Mt provides a hard floor on installed capacity."),
    ("Shyam Metalics", "Supporting",
     "Aggregate installed METAL capacity across intermediate and final products - NOT crude steel",
     "Mtpa", NA, NA, 27.0, "Announced", "FY2031", "S38, S39", "As reported", "Medium",
     "Company-disclosed aggregate installed metal capacity was 13.50 Mtpa at 31-Mar-2024 and 15.13 Mtpa at 31-Dec-2024. A comparable 31-Mar-2026 figure was not located. THIS CONSTRUCT DOUBLE-COUNTS: it sums intermediate products (sponge iron, pellets, billets) and final products, so it must never be compared with a crude steel capacity figure. Announced expansion to ~27 Mtpa by FY2031 with ~USD 1.1bn of capex."),
    ("Godawari Power", "Supporting", "Crude steel capacity", "Mtpa", NA, NA, NA, NA, NA,
     "S30", "Not sourced", "Low",
     "Capacity not disclosed in the sources available within this research cycle. Obtain from the FY2026 annual report."),
    ("APL Apollo", "Supporting", "Structural steel tube capacity - NOT crude steel", "Mtpa",
     NA, NA, NA, NA, NA, "S30", "Not sourced", "Low",
     "Not a crude steel producer. Tube capacity not sourced within this research cycle. Excluded from all crude steel capacity aggregation by design."),
    ("Mukand", "Supporting", "Alloy and specialty steel capacity", "Mtpa", NA, NA, NA, NA, NA,
     "S30", "Not sourced", "Low",
     "Capacity not disclosed in the sources available within this research cycle."),
    ("Gallantt", "Supporting", "Crude steel / billet capacity", "Mtpa", NA, NA, NA, NA, NA,
     "S30", "Not sourced", "Low",
     "Capacity not disclosed in the sources available within this research cycle."),
    ("Uttam Galva", "Supporting", "Cold rolling and galvanising capacity - NOT crude steel",
     "Mtpa", NA, NA, NA, NA, NA, "S36", "Not applicable", "High",
     "Delisted 08-Dec-2022. No current public capacity disclosure. Not a steelmaker."),
    ("Electrosteel / ESL", "Supporting", "Crude steel capacity", "Mtpa", 1.5, 1.5, 3.0,
     "Announced by parent", "End-CY2026", "S35, S43", "As reported", "Medium",
     "Commissioned capacity of 1.5 Mtpa per the company website. The doubling to 3.0 Mtpa by end-CY2026 rests on a single secondary source and should be treated as indicative. Parent group has articulated a 15 Mtpa long-run iron and steel ambition across Bokaro and Goa."),
    ("Kirloskar Ferrous", "Supporting", "Pig iron and castings capacity - NOT crude steel",
     "Mtpa", NA, NA, NA, NA, NA, "S30", "Not sourced", "Low",
     "Predominantly pig iron, castings, alloy steel and seamless tubes. Capacity not sourced within this research cycle."),
]

# ======================================================================================
# 3. PRODUCTION VOLUME
# ======================================================================================
VOLUME_INDUSTRY_HEADERS = [
    "Series", "Unit", "FY2022", "FY2023", "FY2024", "FY2025", "FY2026",
    "Period Type", "Compiler", "Source ID", "Methodology", "Confidence", "Notes",
]

VOLUME_INDUSTRY = [
    ("India crude steel production", "Mt", NA, 127.20, 144.30, 152.18, 168.42,
     "Annual (FY)", "Joint Plant Committee", "S01", "As reported", "High",
     "FY2026 provisional. FY2025 of 152.180 Mt independently confirmed in the Ministry of Steel Annual Report 2025-26 [S06]."),
    ("India total finished steel production", "Mt", 113.60, 123.20, 139.15, 146.69, 161.74,
     "Annual (FY)", "Joint Plant Committee", "S02", "As reported", "High",
     "Alloy/stainless plus non-alloy. June-2026 vintage. The April-2026 vintage shows 160.94 Mt for FY2026 - see Conflict C03."),
    ("of which: SAIL, RINL, NMDC Steel, Tata Steel group, AM/NS, JSW group and Jindal Steel",
     "Mt", 65.06, 72.27, 77.70, 80.08, 88.72,
     "Annual (FY)", "Joint Plant Committee", "S02", "As reported", "High",
     "The integrated majors' share of total finished steel production was 54.9% in FY2026 versus 57.3% in FY2022, i.e. the secondary sector has been growing faster."),
    ("of which: other producers", "Mt", 48.54, 50.93, 61.46, 66.61, 73.02,
     "Annual (FY)", "Joint Plant Committee", "S02", "As reported", "High",
     "The secondary and mid-tier sector. Grew at a 10.7% CAGR over FY2022-FY2026 versus 8.1% for the integrated majors."),
    ("India sponge iron (DRI) production", "Mt", 39.20, 43.62, 51.56, 55.76, 60.30,
     "Annual (FY)", "Joint Plant Committee", "S02", "As reported", "High",
     "India is the world's largest DRI producer. Up 148.8% from 24.24 Mt in FY2015. Structurally important: DRI-EAF is coal-and-gas exposed rather than coking-coal exposed."),
    ("India pig iron production", "Mt", 6.26, 5.86, 7.36, 8.33, 8.37,
     "Annual (FY)", "Joint Plant Committee", "S02", "As reported", "High",
     "Volatile and structurally declining as a share of steelmaking. Peaked around 10.34 Mt in FY2017."),
    ("World crude steel production", "Mt", NA, NA, NA, 1886.76, 1850.21,
     "Calendar Year", "World Steel Association", "S07", "As reported", "High",
     "CALENDAR YEARS: the FY2025 column holds CY2024 and the FY2026 column holds CY2025. CY2025 is provisional. Do not compare directly with the fiscal-year rows above - see Conflict C06."),
    ("China crude steel production", "Mt", NA, NA, NA, 1005.09, 960.81,
     "Calendar Year", "World Steel Association", "S07", "As reported", "High",
     "CALENDAR YEARS as above. China fell 4.4% in CY2025 while India rose 10.4% - the central supply dynamic for global trade flows and for Indian import pressure."),
    ("India crude steel production (calendar year basis)", "Mt", NA, NA, NA, 149.42, 164.89,
     "Calendar Year", "World Steel Association", "S07", "As reported", "High",
     "CALENDAR YEARS as above. Presented alongside the fiscal-year series purely so that the two are never conflated - see Conflict C06."),
]

VOLUME_COMPANY_HEADERS = [
    "Company", "Metric", "Unit", "Reporting Basis", "FY2022", "FY2023", "FY2024",
    "FY2025", "FY2026", "Source ID", "Methodology", "Confidence", "Notes",
]

VOLUME_COMPANY = [
    ("Tata Steel", "Crude / liquid / saleable steel production", "mn t", "Consolidated (global)",
     NA, NA, NA, 30.92, 31.67, "S08", "As reported", "High",
     "Consolidated production is a composite: crude steel for India, liquid steel for UK and Netherlands, saleable steel for South East Asia. Not a like-for-like crude steel figure."),
    ("Tata Steel", "Crude steel production", "mn t", "India (proforma, incl. NINL)",
     NA, NA, NA, 21.68, 23.43, "S08", "As reported", "High",
     "'Best ever' India crude steel production in FY2026, aided by full commissioning of Kalinganagar Phase II."),
    ("Tata Steel", "Deliveries", "mn t", "Consolidated (global)", NA, NA, NA, 30.96, 31.97,
     "S08", "As reported", "High", "The denominator Tata Steel uses for its EBITDA per tonne."),
    ("Tata Steel", "Deliveries", "mn t", "India (proforma, incl. NINL)", NA, NA, NA, 20.94, 22.53,
     "S08", "As reported", "High", "'Best ever' India deliveries of ~22.5 mn t in FY2026."),

    ("JSW Steel", "Crude steel production", "mn t", "Combined operations", NA, NA, NA, 27.79, 30.14,
     "S09", "As reported", "High",
     "'Combined' includes JSW JFE Steel Ltd volumes for 27-31 Mar 2026 only (0.06 mn t). FY2025 includes trial-run production of 0.33 mn t. Consolidated operations excluding the JV were 30.08 mn t in FY2026."),
    ("JSW Steel", "Crude steel production", "mn t", "India operations", NA, NA, NA, 26.98, 29.31,
     "S09", "As reported", "High",
     "India operations = JSW Steel standalone plus Indian subsidiaries plus JVs after eliminations. The separately presented 'Consolidated India Operations' figure is 29.25 mn t."),
    ("JSW Steel", "Saleable steel sales", "mn t", "Combined operations", NA, NA, NA, 26.45, 29.63,
     "S09", "As reported", "High",
     "Up 12.0% year on year; highest ever. Q4FY2026 sales of 7.97 mn t were a record quarter."),
    ("JSW Steel", "Crude steel production - FY2027 guidance", "mn t",
     "Consolidated operations (excl. JSW JFE JV)", NA, NA, NA, NA, 29.75,
     "S09", "As reported (guidance for FY2027)", "High",
     "GUIDANCE FOR FY2027, shown in the FY2026 column for adjacency. Comprises India 28.75 and USA Ohio 1.00. Includes BMM Ispat production of 0.75 mn t; excludes the JSW JFE JV. FY2027 sales guidance is 28.60 mn t."),

    ("SAIL", "Crude steel production", "mn t", "Standalone", NA, NA, NA, 19.17, 19.43,
     "S10", "As reported", "High",
     "JPC's CPSE series shows 19.174 Mt for FY2025 and 19.433 Mt for FY2026, consistent with the company. Implied utilisation on 19.676 Mtpa capacity is 98.8%."),
    ("SAIL", "Saleable steel production", "mn t", "Standalone", NA, NA, NA, 17.94, 19.18,
     "S01", "As reported (JPC CPSE series)", "High",
     "From the Ministry of Steel's CPSE annexure, in lakh tonnes: 179.40 for FY2025 and 191.77 for FY2026, converted to Mt."),
    ("SAIL", "Sales volume", "mn t", "Standalone", NA, NA, NA, 17.89, 19.93,
     "S10", "As reported", "High",
     "Company-reported, up 11.4% year on year - 'best ever'. NOTE: the JPC CPSE annexure shows sales of saleable steel of 18.06 Mt for FY2025 and 20.10 Mt for FY2026, a slightly wider basis. The company figure is used here as it is the audited-filing basis."),

    ("Jindal Steel", "Steel production", "mn t", "Consolidated", NA, NA, NA, 8.12, 9.25,
     "S11", "As reported", "High",
     "Met FY2026 guidance. Strong ramp-up at Angul. FY2027 guidance is 11.0-11.5 mn t."),
    ("Jindal Steel", "Steel sales", "mn t", "Consolidated", NA, NA, NA, 7.97, 8.68,
     "S11", "As reported", "High",
     "The denominator for the company's EBITDA per tonne. FY2027 guidance is 10.5-11.0 mn t. Value-added share was 61% of sales in Q4FY2026; flats were 52%."),

    ("AM/NS India", "Crude steel production", "mn t", "100% basis, calendar year",
     NA, NA, NA, 7.544, 7.219, "S13", "As reported", "High",
     "CALENDAR YEARS: FY2025 column holds CY2024, FY2026 column holds CY2025."),
    ("AM/NS India", "Crude steel production", "mn t", "100% basis, derived fiscal year",
     NA, NA, NA, NA, 7.367, "S13, S14", "Derived - sum of calendar quarters", "Medium",
     "FY2026 derived as 2Q25 + 3Q25 + 4Q25 + 1Q26 = 1.827 + 1.832 + 1.876 + 1.832. A derived FY2025 equivalent is deliberately NOT shown because the 2Q24 and 3Q24 disclosures were not retrieved - see Conflict C16."),
    ("AM/NS India", "Shipments", "mn t", "100% basis, calendar year", NA, NA, NA, 7.933, 7.863,
     "S13", "As reported", "High", "CALENDAR YEARS as above."),
    ("AM/NS India", "Shipments", "mn t", "100% basis, derived fiscal year", NA, NA, NA, NA, 7.975,
     "S13, S14", "Derived - sum of calendar quarters", "Medium",
     "FY2026 derived as 1.775 + 1.939 + 2.267 + 1.994. 2Q CY2026 shipments of 1.93 Mt represent an ~8 Mt annualised run rate, a record for the JV."),

    ("Jindal Stainless", "Deliveries", "mn t", "Consolidated", NA, NA, NA, 2.38, 2.57,
     "S12", "FY2026 as reported; FY2025 derived from the stated +8% growth", "High",
     "FY2026 deliveries of 2.57 mn t, up ~8%. Q4FY2026 was 0.64 mn t, flat year on year. Q4FY2026 grade mix: 200-series ~38%, 300-series ~43%, 400-series ~19%. Exports were 8% of FY2026 sales."),

    ("RINL", "Crude steel production", "mn t", "Standalone", NA, NA, NA, 3.584, 5.429,
     "S01", "As reported (JPC CPSE series)", "High",
     "Up 51% off a depressed FY2025 base as the Government revival package restored operations. The company's own release rounds these to 3.5 and 5.4 Mt."),
    ("RINL", "Liquid steel production", "mn t", "Standalone", NA, NA, NA, 3.749, 5.694,
     "S01", "As reported (JPC CPSE series)", "High", "Up 52%."),
    ("RINL", "Hot metal production", "mn t", "Standalone", NA, NA, NA, 3.913, 5.955,
     "S01", "As reported (JPC CPSE series)", "High", "Up 52%."),
    ("RINL", "Saleable steel production", "mn t", "Standalone", NA, NA, NA, 3.459, 4.501,
     "S01", "As reported (JPC CPSE series)", "High", "Up 30%."),
    ("RINL", "Sales volume", "mn t", "Standalone", NA, NA, NA, 3.4, 4.4,
     "S16", "As reported (rounded by the company)", "Medium",
     "Company release states approximately 4.4 mn t in FY2026 against 3.4 mn t in FY2025, up 27%."),

    ("NMDC Steel (context, not in coverage)", "Crude steel production", "mn t", "Standalone",
     NA, NA, NA, 1.471, 2.382, "S01", "As reported (JPC CPSE series)", "High",
     "Included for completeness of India supply. The 3 Mtpa Nagarnar greenfield CPSE ramped up 61.9% in FY2026; hot rolled coil output was 2.325 Mt."),

    ("Shyam Metalics", "Steel production / sales volume", "mn t", "Consolidated",
     NA, NA, NA, NA, NA, "S31", "Not sourced", "Low",
     "Volumes were not disclosed in the sources available within this research cycle. Obtain from the FY2026 investor presentation or annual report."),
    ("Godawari Power", "Steel production / sales volume", "mn t", "Consolidated",
     NA, NA, NA, NA, NA, "S30", "Not sourced", "Low", "Volumes not sourced within this research cycle."),
    ("APL Apollo", "Tube sales volume", "mn t", "Consolidated", NA, NA, NA, NA, NA,
     "S30", "Not sourced", "Low",
     "Not a crude steel producer. Tube volumes not sourced within this research cycle."),
    ("Mukand", "Steel sales volume", "mn t", "Consolidated", NA, NA, NA, NA, NA,
     "S30", "Not sourced", "Low", "Volumes not sourced within this research cycle."),
    ("Gallantt", "Steel sales volume", "mn t", "Consolidated", NA, NA, NA, NA, NA,
     "S30", "Not sourced", "Low", "Volumes not sourced within this research cycle."),
    ("Uttam Galva", "Sales volume", "mn t", "Not applicable", NA, NA, NA, NA, NA,
     "S36", "Not applicable", "High", "Delisted 08-Dec-2022; no public disclosure."),
    ("Electrosteel / ESL", "Crude steel production", "mn t", "Not applicable", NA, NA, NA, NA, NA,
     "S34", "Not applicable", "High",
     "Vedanta's Q4/FY26 press release does not disclose an ESL steel production line item."),
    ("Kirloskar Ferrous", "Pig iron / castings volume", "mn t", "Consolidated", NA, NA, NA, NA, NA,
     "S30", "Not sourced", "Low", "Volumes not sourced within this research cycle."),
]

# ======================================================================================
# 4. REVENUE  (Rs crore unless stated; consolidated revenue from operations)
# ======================================================================================
REVENUE_HEADERS = [
    "Company", "Coverage Tier", "Metric", "Unit", "Currency", "Reporting Basis",
    "FY2022", "FY2023", "FY2024", "FY2025", "FY2026",
    "FY2026 Company-Headline Revenue (if different)", "FY22-FY26 CAGR",
    "Source ID", "Methodology", "Confidence", "Notes",
]

# (company, tier, metric, unit, ccy, basis, fy22..fy26, headline, srcFY26, srcHist, method, conf, note)
REVENUE = [
    ("Tata Steel", "Core", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     243959, 243353, 229171, 218543, 232140, None,
     "S08 (FY2025-FY2026); S30 (FY2022-FY2024)",
     "As reported; FY2026 verified against the issuer press release", "High",
     "FY2026 revenue of Rs 2,32,140 cr ties exactly to the issuer press release. Group turnover was ~USD 26bn. India revenue was Rs 1,40,302 cr; Netherlands EUR 6,028m; UK GBP 1,978m."),
    ("JSW Steel", "Core", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     146371, 165960, 175006, 168824, 185470, None,
     "S09 (FY2025-FY2026); S30 (FY2022-FY2024)",
     "As reported; FY2026 verified against the issuer presentation", "High",
     "FY2026 of Rs 1,85,470 cr ties exactly. India operations contributed Rs 1,74,854 cr. Q4FY2026 revenue of Rs 51,180 cr was the highest ever quarter."),
    ("SAIL", "Core", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     103477, 104448, 105378, 102479, 110811, None,
     "S10 (FY2025-FY2026); S30 (FY2022-FY2024)",
     "As reported; FY2026 verified against the audited consolidated statement", "High",
     "FY2026 of Rs 1,10,810.84 cr - highest ever. Standalone was Rs 1,10,810 cr, i.e. subsidiaries are immaterial to revenue. See Conflict C09 regarding the Ministry of Steel's Rs 1,01,716 cr FY2025 turnover measure."),
    ("Jindal Steel", "Core", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     51166, 53212, 50354, 50129, 53225, 62412,
     "S30 verified by quarterly summation; S11 for the company headline; S41",
     "As reported; FY2026 verified by summing the four reported quarters", "High",
     "COMPARABILITY WARNING: the company headlines 'Gross Revenue' of Rs 62,412 cr which INCLUDES GST and other income. The comparable statutory figure is Rs 53,225 cr, verified as 12,294 + 11,686 + 13,027 + 16,218. See Conflict C02."),
    ("Jindal Stainless", "Core", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     32733, 35697, 38562, 39312, 42955, None,
     "S30 verified by quarterly summation; S12",
     "As reported; FY2026 verified by summing the four reported quarters", "High",
     "FY2026 of Rs 42,955 cr verified as 10,207 + 10,893 + 10,518 + 11,337. Up 9% year on year on 8% volume growth."),
    ("RINL", "Core", "Turnover", "Rs crore", "INR", "Standalone (basis not specified by issuer)",
     NA, NA, NA, 18280, 22300, None, "S16", "As reported (approximate, rounded by the issuer)",
     "Medium",
     "The issuer release states turnover of 'over Rs 22,300 cr' in FY2026 against 'around Rs 18,280 cr' in FY2025, up 22%. Whether this is revenue from operations or a gross measure is not specified. Audited FY2026 statutory financials were not publicly available at the cutoff."),
    ("Shyam Metalics", "Supporting", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     10394, 12658, 13195, 15138, 18552, None, "S30; S31",
     "As reported; FY2026 cross-checked against reporting of the audited filing", "High",
     "FY2026 of Rs 18,552 cr, up 22%, confirmed by reporting of the 11-May-2026 audited results. Fastest revenue growth in the coverage universe in FY2026."),
    ("Godawari Power", "Supporting", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     5397, 5745, 5445, 5370, 5381, None, "S30", "As reported (aggregator of filings)", "Medium",
     "FY2026 quarterly sum of 1,323 + 1,308 + 1,139 + 1,610 = 5,380 reconciles to the annual column of 5,381. Revenue has been broadly flat for four years while margins stayed above 20%."),
    ("APL Apollo", "Supporting", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     13063, 16166, 18119, 20690, 23079, None, "S30", "As reported (aggregator of filings)", "Medium",
     "Downstream tube converter, not a steelmaker. Grew revenue every year across FY2022-FY2026, the only company in the universe to do so."),
    ("Mukand", "Supporting", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     4643, 5568, 5175, 4890, 4890, None, "S30", "As reported (aggregator of filings)", "Medium",
     "FY2026 quarterly sum of 1,129 + 1,161 + 1,329 + 1,269 = 4,888 reconciles to the annual column. FY2025 and FY2026 revenue are coincidentally identical."),
    ("Gallantt", "Supporting", "Revenue from operations", "Rs crore", "INR", "Consolidated",
     3017, 4057, 4227, 4293, 4419, None, "S30", "As reported (aggregator of filings)", "Medium",
     "Annual column used. The sum of the four FY2026 quarters is Rs 4,438 cr, a Rs 19 cr difference - see Conflict C13. Pre-merger periods are not like-for-like."),
    ("Uttam Galva", "Supporting", "Revenue from operations", "Rs crore", "INR",
     "Not applicable - delisted", 840, NA, NA, NA, NA, None, "S36", "Not applicable", "High",
     "Delisted 08-Dec-2022 following the NCLT-approved resolution plan of 14-Oct-2022. No public financial statements from FY2023 onwards. FY2022 shown as the last publicly available period."),
    ("Electrosteel / ESL", "Supporting", "Revenue from operations", "Rs crore", "INR",
     "Not applicable - delisted", NA, NA, NA, NA, NA, None, "S34, S35", "Not applicable", "High",
     "Equity delisted following IBC resolution; now a Vedanta subsidiary. Vedanta's Q4/FY26 press release does not disclose a separate ESL revenue line. The FY2026 ESL annual report was not publicly available at the cutoff."),
    ("Kirloskar Ferrous", "Supporting", "Revenue from operations", "Rs crore", "INR",
     "Consolidated", 3748, 6417, 6146, 6564, 6889, None, "S30",
     "As reported (aggregator of filings)", "Medium",
     "FY2026 quarterly sum of 1,698 + 1,755 + 1,618 + 1,817 = 6,888 reconciles to the annual column. The FY2022 to FY2023 step-up reflects the ISMT consolidation."),
]

REVENUE_USD = [
    ("AM/NS India", "Core", "Sales", "US$ m", "USD", "100% basis, calendar year",
     NA, NA, NA, 6515, 6026, None, "S13", "As reported", "High",
     "CALENDAR YEARS: the FY2025 column holds CY2024 and the FY2026 column holds CY2025. Sales fell 7.5% in CY2025 on lower average selling prices despite broadly flat shipments."),
    ("AM/NS India", "Core", "Sales", "US$ m", "USD", "100% basis, derived fiscal year",
     NA, NA, NA, NA, 6196, None, "S13, S14", "Derived - sum of calendar quarters", "Medium",
     "FY2026 derived as 1,489 + 1,496 + 1,593 + 1,618. Not a company-reported fiscal-year figure - see Conflict C16. 2Q CY2026 sales were USD 1.66bn, up 11.3% year on year."),
]

# ======================================================================================
# 5. EBITDA
# ======================================================================================
EBITDA_HEADERS = [
    "Company", "Coverage Tier", "Unit", "Currency", "Reporting Basis",
    "EBITDA Definition Used By Company", "Other Income Included In Reported EBITDA?",
    "Reported FY2025", "Reported FY2026",
    "Standardised FY2022", "Standardised FY2023", "Standardised FY2024",
    "Standardised FY2025", "Standardised FY2026",
    "Standardised FY2026 Margin", "Source ID", "Methodology", "Confidence", "Notes",
]

EBITDA = [
    ("Tata Steel", "Core", "Rs crore", "INR", "Consolidated",
     "Company-reported consolidated EBITDA; also discloses an Adjusted EBITDA excluding FX movement on intercompany debt and receivables",
     "Partly", 25802, 34848, 63490, 32300, 22248, 25298, 34352,
     "S08 (reported); S30 (standardised)", "As reported and cross-checked", "High",
     "Reported FY2026 EBITDA of Rs 34,848 cr, up 35%. Adjusted EBITDA was Rs 34,640 cr. India EBITDA Rs 34,272 cr at a 24% margin; Netherlands EUR 267m; UK a loss of GBP 217m. Cost transformation delivered ~Rs 10,868 cr of benefit and margin expanded 320bps. The Rs 496 cr gap to standardised reflects other operating items."),
    ("JSW Steel", "Core", "Rs crore", "INR", "Consolidated",
     "Company-reported EBITDA; also discloses an Adjusted EBITDA excluding unrealised FX on long-term borrowings net of unrealised FX on intercompany receivables",
     "Partly", 22904, 29821, 39114, 18470, 28157, 22725, 29464,
     "S09 (reported); S30 (standardised)", "As reported and cross-checked", "High",
     "Reported FY2026 EBITDA of Rs 29,821 cr; Adjusted EBITDA Rs 32,048 cr (FY2025: Rs 22,964 cr). India operations reported Rs 29,240 cr. Q4FY2026 reported EBITDA Rs 8,634 cr at a 16.9% margin. FY2026 PAT of Rs 25,508 cr includes an Rs 18,051 cr gain on the BPSL slump sale; normalised PAT excluding exceptionals was Rs 8,698 cr."),
    ("SAIL", "Core", "Rs crore", "INR",
     "Reported EBITDA is STANDALONE; standardised series is consolidated",
     "Company-reported EBITDA disclosed on a standalone basis in the results press release",
     "Yes (in the consolidated derivation)", 11764, 13146,
     21363, 8038, 11149, 10690, 12000,
     "S10 (reported); S30 (standardised)", "As reported and cross-checked", "High",
     "BASIS MISMATCH - handle with care. Rs 13,146 cr is the FY2026 STANDALONE headline. Consolidated EBITDA including other income derives to Rs 12,894 cr (profit before exceptionals, JV share and tax of Rs 4,748 cr plus finance cost Rs 2,158 cr plus depreciation Rs 5,988 cr). Excluding other income of Rs 894 cr gives the standardised Rs 12,000 cr. All three reconcile - see Conflict C09. Do not pair a consolidated enterprise value with the standalone headline."),
    ("Jindal Steel", "Core", "Rs crore", "INR", "Consolidated",
     "Company headlines an Adjusted EBITDA that strips out FX gains",
     "No", 9339, 9660, 15559, 9942, 10202, 9488, 9644,
     "S11 (reported); S30 (standardised)", "As reported and cross-checked", "High",
     "Company-headlined Adjusted EBITDA was Rs 9,099 cr for FY2026 (FY2025: Rs 9,339 cr), adjusted for an FX gain of Rs 561 cr. Adding the FX gain back gives reported EBITDA of Rs 9,660 cr, which sits within Rs 16 cr of the standardised Rs 9,644 cr - a clean reconciliation. EBITDA fell 3% despite 14% volume growth, i.e. FY2026 was a price-and-cost-driven margin compression year."),
    ("Jindal Stainless", "Core", "Rs crore", "INR", "Consolidated",
     "Company-reported consolidated EBITDA", "No", 4670, 5560,
     5090, 3586, 4511, 4469, 5560,
     "S12 (reported); S30 (standardised)", "As reported and cross-checked", "High",
     "Reported FY2026 EBITDA of Rs 5,560 cr, up ~19%, stated on the exchange-filed earnings call. This sits within Rs 1 cr of the standardised Rs 5,561 cr, confirming Jindal Stainless EXCLUDES other income from EBITDA. Reported FY2025 of Rs 4,670 cr is derived from the stated +19% growth and is therefore approximate. Q4FY2026 EBITDA Rs 1,455 cr, up 37%."),
    ("RINL", "Core", "Rs crore", "INR", "Not applicable", "Not disclosed", "Not applicable",
     NA, NA, NA, NA, NA, NA, NA, "S16", "Not applicable", "High",
     "RINL is unlisted and wholly Government-owned. Audited FY2026 statutory financials, and therefore EBITDA, were NOT publicly available at the cutoff. The only profitability datapoint located is a monthly cash profit of Rs 54 cr in Jan-2026, against a cash loss of Rs 486 cr in Sep-2024."),
    ("Shyam Metalics", "Supporting", "Rs crore", "INR", "Consolidated",
     "Company-reported EBITDA INCLUDES other income", "Yes", NA, 2537,
     2601, 1499, 1570, 1866, 2333, "S31 (reported); S30 (standardised)",
     "As reported and reconciled", "High",
     "EXACT RECONCILIATION: standardised Rs 2,333 cr plus FY2026 other income of Rs 204 cr equals the reported Rs 2,537 cr. This is the clearest example in the universe of why two EBITDA columns are necessary - see Conflict C10. Reported FY2025 EBITDA is not asserted; the company states +21% growth, which would imply roughly Rs 2,096 cr."),
    ("Godawari Power", "Supporting", "Rs crore", "INR", "Consolidated", "Not sourced", "Unknown",
     NA, NA, 1868, 1134, 1328, 1194, 1253, "S30", "Standardised only", "Medium",
     "Highest standardised margin in the universe at ~23% in FY2026, reflecting captive iron ore. A company-reported EBITDA was not located, so only the standardised basis is shown."),
    ("APL Apollo", "Supporting", "Rs crore", "INR", "Consolidated", "Not sourced", "Unknown",
     NA, NA, 946, 1022, 1193, 1199, 1802, "S30", "Standardised only", "Medium",
     "Margin structurally low at 6-8% because this is a conversion business on purchased HRC, not an integrated producer. FY2026 standardised EBITDA rose 50% as HRC costs fell for most of the year - the mirror image of the integrated mills."),
    ("Mukand", "Supporting", "Rs crore", "INR", "Consolidated", "Not sourced", "Unknown",
     NA, NA, 239, -172, 293, 285, 172, "S30", "Standardised only", "Medium",
     "FY2026 standardised EBITDA of Rs 172 cr sits far below profit before tax of Rs 512 cr and net profit of Rs 604 cr, indicating a material non-operating or exceptional item. DO NOT use FY2026 Mukand earnings in operating comparisons - see Conflict C11."),
    ("Gallantt", "Supporting", "Rs crore", "INR", "Consolidated", "Not sourced", "Unknown",
     NA, NA, 296, 364, 448, 694, 716, "S30", "Standardised only", "Medium",
     "Margin roughly doubled from 10% in FY2022 to 16% in FY2026, the largest margin expansion in the supporting set."),
    ("Uttam Galva", "Supporting", "Rs crore", "INR", "Not applicable - delisted",
     "Not applicable", "Not applicable", NA, NA, -57, NA, NA, NA, NA,
     "S36", "Not applicable", "High",
     "FY2022 standardised EBITDA was negative Rs 57 cr, the last publicly available period. Delisted 08-Dec-2022."),
    ("Electrosteel / ESL", "Supporting", "Rs crore", "INR", "Not applicable - delisted",
     "Not applicable", "Not applicable", NA, NA, NA, NA, NA, NA, NA,
     "S34, S35", "Not applicable", "High",
     "Vedanta's Q4/FY26 press release does not disclose a separate ESL EBITDA line item, and the FY2026 ESL annual report was not publicly available at the cutoff."),
    ("Kirloskar Ferrous", "Supporting", "Rs crore", "INR", "Consolidated", "Not sourced",
     "Unknown", NA, NA, 643, 836, 857, 762, 850, "S30", "Standardised only", "Medium",
     "FY2026 net profit of Rs 507 cr exceeds profit before tax of Rs 497 cr, indicating a net tax credit - see Conflict C12. Use profit before tax for normalised work on this name."),
]

EBITDA_USD = [
    ("AM/NS India", "Core", "US$ m", "USD", "100% basis, calendar year",
     "EBITDA as disclosed by ArcelorMittal S.A. for the joint venture", "Not disclosed",
     844, 684, NA, NA, NA, 844, 684, "S13", "As reported", "High",
     "CALENDAR YEARS: the FY2025 columns hold CY2024 and the FY2026 columns hold CY2025. EBITDA fell 19% in CY2025 on a negative price-cost effect. Quarterly: 1Q25 101, 2Q25 200, 3Q25 217, 4Q25 166, 1Q26 195, 2Q26 257."),
    ("AM/NS India", "Core", "US$ m", "USD", "100% basis, derived fiscal year",
     "EBITDA as disclosed by ArcelorMittal S.A. for the joint venture", "Not disclosed",
     NA, 778, NA, NA, NA, NA, 778, "S13, S14", "Derived - sum of calendar quarters", "Medium",
     "FY2026 derived as 200 + 217 + 166 + 195. Not a company-reported fiscal-year figure - see Conflict C16. 2Q CY2026 EBITDA of USD 257m was up 28.5% year on year."),
]

# ======================================================================================
# 6. EBITDA PER TON
# ======================================================================================
EBITDA_PT_HEADERS = [
    "Company", "Basis / Segment", "Unit", "Currency", "Volume Denominator",
    "FY2025", "FY2026", "Q3FY2026", "Q4FY2026", "FY2027 Guidance",
    "Source ID", "Methodology", "Confidence", "Notes",
]

EBITDA_PT = [
    ("Tata Steel", "Consolidated (global), reported EBITDA", "Rs/t", "INR",
     "Deliveries (consolidated)", 8335, 10900, 10116, 11410, NA,
     "S08", "As reported", "High",
     "Company-disclosed. FY2026 Rs 10,900/t equates to USD 124/t. Adjusted EBITDA per tonne was Rs 10,835/t for FY2026 and Rs 8,441/t for FY2025."),
    ("Tata Steel", "India (proforma, incl. NINL), reported EBITDA", "Rs/t", "INR",
     "Deliveries (India)", 13983, 15213, 13735, 15907, NA,
     "S08", "As reported", "High",
     "Company-disclosed. FY2026 Rs 15,213/t equates to USD 172/t - the highest India EBITDA per tonne in the coverage universe on a company-reported basis. Q4FY2026 reached Rs 15,907/t."),
    ("JSW Steel", "Consolidated, reported EBITDA", "Rs/t", "INR",
     "Saleable steel sales (combined operations)", 8661, 10064, NA, 10833, NA,
     "S09", "Computed", "High",
     "COMPUTED, not company-disclosed: FY2026 Rs 29,821 cr divided by 29.63 mn t; FY2025 Rs 22,904 cr divided by 26.45 mn t; Q4FY2026 Rs 8,634 cr divided by 7.97 mn t. On Adjusted EBITDA the FY2026 figure would be Rs 10,816/t."),
    ("JSW Steel", "India operations, reported EBITDA", "Rs/t", "INR",
     "Steel sales (India operations)", 8924, 10167, NA, 10795, NA,
     "S09", "Computed", "High",
     "COMPUTED: FY2026 Rs 29,240 cr divided by 28.76 mn t; FY2025 Rs 22,908 cr divided by 25.67 mn t; Q4FY2026 Rs 8,463 cr divided by 7.84 mn t."),
    ("SAIL", "Standalone, reported EBITDA", "Rs/t", "INR", "Sales volume (standalone)",
     6576, 6596, 5107, 8951, NA, "S10", "Computed", "High",
     "COMPUTED: FY2026 Rs 13,146 cr divided by 19.93 mn t; FY2025 Rs 11,764 cr divided by 17.89 mn t; Q4FY2026 Rs 4,762 cr divided by 5.32 mn t; Q3FY2026 Rs 2,630 cr divided by 5.15 mn t. Sell-side estimates of Q4FY2026 EBITDA per tonne cluster around Rs 8,280/t on a crude-steel-production denominator, illustrating how sensitive this metric is to the denominator chosen."),
    ("Jindal Steel", "Consolidated, Adjusted EBITDA", "Rs/t", "INR", "Steel sales",
     11712, 10482, 6981, 10093, NA, "S11", "As reported", "High",
     "Company-disclosed on Adjusted EBITDA (excluding FX gains). Verification: Rs 9,099 cr divided by 8.68 mn t equals Rs 10,482/t. Fell 11% year on year - the sharpest per-tonne compression among the core names, despite 14% volume growth."),
    ("Jindal Stainless", "Consolidated, reported EBITDA", "Rs/t", "INR", "Deliveries",
     19622, 21634, NA, 22734, "Rs 18,000-20,000/t",
     "S12", "Computed; guidance as reported", "High",
     "COMPUTED: FY2026 Rs 5,560 cr divided by 2.57 mn t; Q4FY2026 Rs 1,455 cr divided by 0.64 mn t. FY2025 uses the derived 2.38 mn t denominator and is therefore approximate. Management guided FY2027 EBITDA per tonne to Rs 18,000-20,000 with 7-9% volume growth - i.e. guidance is BELOW the FY2026 outcome, an explicit signal of expected margin normalisation. Highest per-tonne EBITDA in the universe, reflecting the stainless product mix rather than superior operating efficiency."),
    ("AM/NS India", "100% basis, derived fiscal year", "US$/t", "USD",
     "Shipments", NA, 97.6, NA, NA, NA,
     "S13, S14", "Derived - sum of calendar quarters, then divided", "Medium",
     "DERIVED: USD 778m divided by 7.975 mn t for FY2026. Calendar-year equivalents are USD 106.4/t for CY2024 (844/7.933) and USD 87.0/t for CY2025 (684/7.863). No FY2025 figure is shown because the derived FY2025 volume and EBITDA are not available - see Conflict C16. For comparison, Tata Steel India was USD 172/t and the Tata Steel group USD 124/t in FY2026."),
    ("RINL", "Standalone", "Rs/t", "INR", "Not applicable", NA, NA, NA, NA, NA,
     "S16", "Not applicable", "High",
     "EBITDA is not publicly available for RINL, so EBITDA per tonne cannot be computed."),
    ("Shyam Metalics", "Consolidated", "Rs/t", "INR", "Not available", NA, NA, NA, NA, NA,
     "S31", "Not computable", "Low",
     "Company-reported EBITDA is available (Rs 2,537 cr for FY2026) but sales volume was not disclosed in the sources available, so a per-tonne figure cannot be struck. Do not infer one."),
    ("Godawari Power", "Consolidated", "Rs/t", "INR", "Not available", NA, NA, NA, NA, NA,
     "S30", "Not computable", "Low", "Volumes not sourced within this research cycle."),
    ("APL Apollo", "Consolidated", "Rs/t", "INR", "Not applicable", NA, NA, NA, NA, NA,
     "S30", "Not applicable", "High",
     "A tube converter, not a crude steel producer. An EBITDA per tonne of crude steel is meaningless for this company and is deliberately not presented. EBITDA per tonne of tube sold would be the appropriate analogue if volumes were sourced."),
    ("Mukand", "Consolidated", "Rs/t", "INR", "Not available", NA, NA, NA, NA, NA,
     "S30", "Not computable", "Low", "Volumes not sourced within this research cycle."),
    ("Gallantt", "Consolidated", "Rs/t", "INR", "Not available", NA, NA, NA, NA, NA,
     "S30", "Not computable", "Low", "Volumes not sourced within this research cycle."),
    ("Uttam Galva", "Not applicable - delisted", "Rs/t", "INR", "Not applicable",
     NA, NA, NA, NA, NA, "S36", "Not applicable", "High", "Delisted 08-Dec-2022."),
    ("Electrosteel / ESL", "Not applicable - delisted", "Rs/t", "INR", "Not applicable",
     NA, NA, NA, NA, NA, "S34", "Not applicable", "High",
     "Neither EBITDA nor volumes are separately disclosed by the parent."),
    ("Kirloskar Ferrous", "Consolidated", "Rs/t", "INR", "Not available", NA, NA, NA, NA, NA,
     "S30", "Not computable", "Low", "Volumes not sourced within this research cycle."),
]
