# -*- coding: utf-8 -*-
"""Source registry, data dictionary and conflicts log.

Every figure in the workbook carries a Source ID that resolves to exactly one row of
SOURCES. Source IDs are stable and must never be re-pointed at a different document;
if a document is superseded, add a new ID and retire the old one in NOTES.
"""

# Tier 1 = primary (issuer / government / official statistical agency)
# Tier 2 = secondary (rating agency, sell-side, specialist price reporting agency)
# Tier 3 = tertiary (aggregator of filings, general press)

SOURCE_HEADERS = [
    "Source ID", "Tier", "Source Type", "Publisher / Issuer", "Publication",
    "Publication / Filing Date", "Section / Page Reference", "Period Covered",
    "URL", "Verification Status", "Access Date", "Notes",
]

SOURCES = [
    ("S01", 1, "Government statistical release", "Ministry of Steel, Government of India",
     "Monthly Economic Report for the month of March, 2026",
     "Apr-2026", "Paras 1-10; Annexure-I p.7; Annexure-II p.8; Annexure-III p.9",
     "FY2023-FY2026 (FY2026 provisional)",
     "https://www.steel.gov.in/sites/default/files/2026-04/Monthly%20Economic%20Report-%20March%202026%20(5).pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Underlying data compiler is the Joint Plant Committee (JPC). This is the April-2026 data vintage."),

    ("S02", 1, "Government statistical release", "Ministry of Steel, Government of India",
     "Development of Indian Steel Sector since 2014-15",
     "Jun-2026", "Sections (a)-(e) and capacity paragraph, pp.1-14",
     "FY2015-FY2026 (FY2026 provisional)",
     "https://steel.gov.in/sites/default/files/2026-06/Development%20of%20Indian%20Steel%20Sector%20since%202014-15_0.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Later data vintage than S01; used for the long-run series. Bilingual document; English tables used."),

    ("S03", 1, "Government statistical release", "Ministry of Steel, Government of India",
     "An Overview of Steel Sector for the month of June, 2026",
     "Jul-2026", "Global Scenario; Domestic Scenario",
     "FY2026; CY2024-CY2025",
     "https://steel.gov.in/sites/default/files/2026-07/An%20Overview%20of%20Steel%20Sector%20for%20the%20month%20of%20June,%202026.pdf",
     "Verified - retrieved via search snippet and cross-checked against S02", "03-Aug-2026",
     "Source of crude steel capacity 220.4 Mt (FY2026) and per-capita consumption 115.7 kg (FY2026)."),

    ("S04", 1, "Government statistical release", "Ministry of Steel, Government of India",
     "An Overview of Steel Sector (March 2026)",
     "Apr-2026", "Global Scenario; Domestic Scenario",
     "FY2026; CY2024-CY2025",
     "https://steel.gov.in/sites/default/files/2026-04/An%20Overview%20of%20Steel%20Sector%20(Mar.%202026)%20(2).pdf",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Earlier vintage of S03; states capacity 220.3 Mt and per-capita 115 kg. Retained to evidence Conflict C04/C05."),

    ("S05", 1, "Government statistical release", "Ministry of Steel, Government of India",
     "Monthly Economic Report for the month of June, 2026",
     "Jul-2026", "Paras 1-4",
     "Q1 FY2027 (Apr-Jun 2026)",
     "https://steel.gov.in/sites/default/files/2026-07/Monthly%20Economic%20Report-%20June%202026%20(1).pdf",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Latest available monthly vintage at the data cutoff. Source of Q1 FY2027 consumption 41.57 Mt."),

    ("S06", 1, "Government annual report", "Ministry of Steel, Government of India",
     "Annual Report 2025-26", "Apr-2026", "Crude steel production section",
     "FY2021-FY2025",
     "https://steel.gov.in/sites/default/files/2026-04/Final%20Annual%20Report%202025-26%20(English%20Version).pdf",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Confirms FY2025 crude steel 152.180 Mt, +5.4% over FY2024 144.299 Mt."),

    ("S07", 1, "International statistical agency", "World Steel Association (worldsteel)",
     "Monthly crude steel production statistics, as reproduced in Annexure-II of S01",
     "Apr-2026", "Annexure-II, p.8", "CY2024-CY2025 and monthly to Feb-2026",
     "https://www.steel.gov.in/sites/default/files/2026-04/Monthly%20Economic%20Report-%20March%202026%20(5).pdf",
     "Verified - table extracted from S01", "03-Aug-2026",
     "CY2025 figures are provisional per worldsteel. Calendar-year basis - NOT comparable to Indian fiscal years."),

    ("S08", 1, "Issuer results release", "Tata Steel Limited",
     "4QFY2026 Press Release - Consolidated results for the twelve months ended 31 March 2026",
     "15-May-2026", "Financial Highlights table, p.2; Management Comments pp.2-3",
     "4QFY2026, 3QFY2026, 4QFY2025, FY2026, FY2025",
     "https://www.tatasteel.com/media/25700/4qfy2026-press-release.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "'India' = Tata Steel Standalone + Neelachal Ispat Nigam Ltd on proforma basis adjusted for intercompany purchase and sale."),

    ("S09", 1, "Issuer investor presentation (exchange filed)", "JSW Steel Limited",
     "Q4 FY26 Investor / Analyst Presentation, filed with NSE and BSE under Reg. 30",
     "14-May-2026", "pp.5, 6, 8, 33, 34, 40, 44, 45, 46, 48",
     "Q4FY2026, Q3FY2026, Q4FY2025, FY2026, FY2025; FY2027 guidance",
     "https://nsearchives.nseindia.com/corporate/jessydenny_14052026164431_JSW_Steel_Q4_FY26_vF.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "BPSL steel business deconsolidated from 27-Mar-2026; 'Combined Operations' includes JSW JFE Steel Ltd volumes for 27-31 Mar 2026 only."),

    ("S10", 1, "Issuer audited results + press release (exchange filed)",
     "Steel Authority of India Limited",
     "Audited Financial Results for the quarter and year ended 31 March 2026 and Press Release",
     "15-May-2026", "Consolidated statement of profit and loss; Press Release pp.49-50",
     "Q4FY2026, Q3FY2026, Q4FY2025, FY2026, FY2025",
     "https://www.sail.co.in/sites/default/files/2026-05/Financial%20Results%20for%20FY%202025-26%20and%20recommendation%20of%20Final%20Dividend.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "CRITICAL: SAIL's press-release EBITDA/PAT summary table is STANDALONE. Consolidated figures taken from the audited consolidated statement in the same filing."),

    ("S11", 1, "Issuer investor presentation (exchange filed)", "Jindal Steel Limited",
     "Q4 FY26 Investor Presentation, filed with NSE", "02-May-2026",
     "pp.5, 6, 11, 12, 13, 14", "Q4FY2026, Q3FY2026, Q4FY2025, FY2026, FY2025; FY2027 guidance",
     "https://nsearchives.nseindia.com/corporate/JINDALSTEL_02052026120643_stx_02052026.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "CRITICAL: company headline 'Gross Revenue' INCLUDES GST and other income and is not peer-comparable. See Conflict C02."),

    ("S12", 1, "Issuer earnings call transcript (exchange filed)", "Jindal Stainless Limited",
     "4QFY26 Earnings Conference Call transcript, filed with NSE under Reg. 30",
     "Call 05-May-2026; filed 09-May-2026", "Management remarks by MD and by Mr. Tarun Khulbe, pp.3-5",
     "Q4FY2026, FY2026; FY2027 guidance",
     "https://nsearchives.nseindia.com/corporate/JSL_09052026134409_JSLSEintimationtranscriptssd.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Primary confirmation of FY2026 consolidated EBITDA Rs 5,560 cr, PAT Rs 3,185 cr, deliveries 2.57 Mt, net debt Rs 3,040 cr."),

    ("S13", 1, "Issuer results release", "ArcelorMittal S.A.",
     "Fourth quarter 2025 and full year 2025 results - earnings release", "04-Feb-2026",
     "'AMNS India' section", "4Q25, 3Q25, 4Q24, 12M25, 12M24",
     "https://cms.arcelormittal.com/media/hzbg231b/4q25-arcelormittal-earnings-release.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "AMNS India disclosed on a 100% basis in USD on CALENDAR quarters. ArcelorMittal holds a 60% equity interest."),

    ("S14", 1, "Issuer results release", "ArcelorMittal S.A.",
     "First quarter 2026 results - earnings release", "30-Apr-2026",
     "'AMNS India' section, five-quarter table", "1Q26, 4Q25, 3Q25, 2Q25, 1Q25",
     "https://cdn.arcelormittal.com/media/dqjcxaz3/1q26-earnings-release-final.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Provides the quarterly series used to derive an Apr-Mar fiscal-year equivalent for AM/NS India."),

    ("S15", 1, "Issuer results release", "ArcelorMittal S.A.",
     "Second quarter 2026 results", "30-Jul-2026", "'AMNS India' section",
     "2Q26 (Apr-Jun 2026)",
     "https://corporate.arcelormittal.com/media/news/regulatory-news/arcelormittal-reports-second-quarter-2026-results",
     "Partially verified - headline figures via issuer release and Business Standard report of it; full PDF table not retrieved",
     "03-Aug-2026",
     "2Q26 AMNS India EBITDA US$257m; sales US$1.66bn; shipments 1.93 Mt; production 1.95 Mt."),

    ("S16", 1, "Issuer / public-authority press release",
     "Rashtriya Ispat Nigam Limited (Visakhapatnam Steel Plant), via Visakhapatnam Port Authority / PTI",
     "FY2025-26 performance press release", "01-Apr-2026", "Statement of DGM J Mallikarjun Rao",
     "FY2026, FY2025", "https://infra.economictimes.indiatimes.com/news/construction/vizag-steel-plant-achieves-record-production-and-sales-growth-in-fy26/129957199",
     "Verified - full article text retrieved", "03-Aug-2026",
     "RINL is unlisted and wholly Government-owned; audited FY2026 statutory financials were not public at the cutoff."),

    ("S17", 1, "Official commodity price data", "World Bank",
     "Commodity Price Data ('The Pink Sheet') - CMO Historical Data, Monthly",
     "Workbook stamped 'Updated on July 02, 2026'",
     "Sheet 'Monthly Prices'; definitions on sheet 'Description' rows 4, 90 and 91",
     "1960M01 to 2026M06",
     "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Historical-Data-Monthly.xlsx",
     "Verified - workbook downloaded and parsed programmatically", "03-Aug-2026",
     "Iron ore = any origin fines, spot, CFR China, 62% Fe. Coal (Australia) = THERMAL, Newcastle 6000 kcal/kg futures FOB - NOT coking coal."),

    ("S18", 1, "Official commodity price data", "World Bank",
     "Commodity Price Data ('The Pink Sheet') - CMO Historical Data, Annual",
     "Workbook stamped 'Updated on March 03, 2026'", "Sheet 'Annual Prices (Nominal)'",
     "1960 to 2025",
     "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Historical-Data-Annual.xlsx",
     "Verified - workbook downloaded and parsed programmatically", "03-Aug-2026",
     "Calendar-year averages. Annual file is a March-2026 vintage so it stops at CY2025."),

    ("S19", 2, "Rating agency research", "ICRA Limited (an affiliate of Moody's)",
     "Indian steel sector research notes (report references 6790 and 6940)",
     "Apr-2026 (report 6940); earlier vintage report 6790", "Domestic HRC price commentary",
     "FY2026 quarterly; early FY2027", "https://www.icra.in/Research/ViewResearchReport/6940",
     "Partially verified - figures taken from published research summaries; full report is subscriber-gated",
     "03-Aug-2026",
     "Source of the FY2026 HRC price path and the Apr-2026 US$29-45/MT import-parity discount."),

    ("S20", 2, "Sell-side sector research", "IDBI Capital Markets & Securities Ltd",
     "Metals & Mining - Sector Update", "09-Apr-2026", "Summary and Key Highlights, p.1; Exhibits 5-10",
     "Mar-2026 monthly", "https://idbicapital.com/InstitutionReports/Uploads/Metals_Mining_SU_09042026.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Broker assessment. Coking coal level differs materially from the Ministry of Steel series - see Conflict C01."),

    ("S21", 2, "Sell-side commodity tracker", "IDBI Capital Markets & Securities Ltd / IDBI Direct",
     "Commodity Price Update", "22-Jun-2026", "Price table rows for HRC, iron ore, pellets, coking coal",
     "Week ended 22-Jun-2026, with 52-week ranges",
     "https://idbidirect.in/IDBIAdmin/Pdf/Commodity_Price_Update_SU_22062026-22-June-2026-1061890911.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Weekly spot snapshot with 52-week high/low, useful for range discipline in valuation sensitivities."),

    ("S22", 2, "Price reporting agency", "BigMint (formerly SteelMint)",
     "India steel index commentary", "31-Jul-2026", "BF-rebar benchmark assessment",
     "Week ended 31-Jul-2026",
     "https://www.bigmint.co/insights/detail/bigmint-s-india-steel-index-rises-w-o-w-amid-tightening-supplies-inventory-restocking-776279",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Rebar IS 1786 Fe 550D, 12-32 mm, BF route, ex-Mumbai, distributor-to-dealer, EXCLUDING 18% GST."),

    ("S23", 1, "Issuer regulatory filing", "NMDC Limited",
     "Iron ore price revision intimations filed with BSE / NSE",
     "Various: filings effective 05-Apr-2026, 06-May-2026 and 10-Jul-2026",
     "Price fixation statements", "FY2027 to date",
     "https://infra.economictimes.indiatimes.com/news/construction/nmdc-hikes-iron-ore-prices-by-up-to-11-1/130056492",
     "Partially verified - filing content quoted in press reports; original BSE filings not directly retrieved",
     "03-Aug-2026",
     "Notified ex-mine prices for Bailadila grades; exclude royalty, DMF, NMET, cess and other levies unless stated."),

    ("S24", 1, "Parliamentary answer", "Ministry of Steel, Government of India",
     "Lok Sabha Unstarred Question No. 5098 - Production Linked Incentive Scheme for Specialty Steel",
     "Answered 24-Mar-2026", "Answer to parts (a)-(d)", "PLI Rounds 1-3, cumulative to Mar-2026",
     "https://sansad.in/getFile/loksabhaquestions/annex/187/AU5098_BI0By2.pdf?source=pqals",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Answered by Minister of State Shri Bhupathiraju Srinivasa Varma. Highest-authority source for PLI progress."),

    ("S25", 1, "Parliamentary answer", "Ministry of Steel, Government of India",
     "Rajya Sabha Unstarred Question No. 3350 - Green Steel Plant in Salav, Raigarh",
     "Answered 20-Mar-2026", "Answer to parts (a)-(d), items (i)-(vi)",
     "Policy measures in force as at Mar-2026",
     "https://steel.gov.in/sites/default/files/2026-04/ru%203350.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Confirms Green Steel Taxonomy notification date 23-Dec-2024, safeguard-duty tariff headings, CVD and Budget 2026-27 measures."),

    ("S26", 1, "Parliamentary answer", "Ministry of Steel, Government of India",
     "Rajya Sabha Unstarred Question No. 3982 - Status of SAIL Steel Plants in India",
     "Answered 27-Mar-2026", "Answer to part (a) plant-wise table; parts (b)-(d)",
     "FY2021-FY2025 average; capacity as at Mar-2026",
     "https://www.steel.gov.in/sites/default/files/2026-04/ru%203982.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Authoritative plant-wise SAIL capacity and utilisation, plus Board-approved expansion quanta."),

    ("S27", 1, "Gazette notification", "Ministry of Finance, Government of India",
     "Safeguard duty notification imposing definitive duty on non-alloy and alloy steel flat products",
     "30-Dec-2025", "Rate schedule and periods",
     "21-Apr-2025 to 20-Apr-2028",
     "https://mail.caalley.com/cus25/cssg02-2025.pdf",
     "Partially verified - terms corroborated by Argus, Livemint and Economic Times reports of the notification, and by S25",
     "03-Aug-2026",
     "12% (year 1), 11.5% (year 2), 11% (year 3), with provision for a mid-term review."),

    ("S28", 1, "Trade-remedy determination",
     "Directorate General of Trade Remedies (DGTR), Ministry of Commerce & Industry",
     "Final findings, safeguard investigation into imports of non-alloy and alloy steel flat products",
     "18-Aug-2025", "Findings and recommendation", "Investigation period to 2025",
     "https://www.spglobal.com/energy/en/news-research/latest-news/metals/081825-indias-dgtr-recommends-3-year-safeguard-duty-on-steel-flat-products",
     "Partially verified - recommendation terms corroborated by S&P Global, Times of India and Economic Times",
     "03-Aug-2026",
     "DGTR found 'a recent, sudden, sharp and significant increase in imports of the product under consideration'."),

    ("S29", 1, "Gazette notification", "Ministry of Finance, Government of India",
     "Provisional safeguard duty of 12% for 200 days on five categories of steel flat products",
     "21-Apr-2025", "Notification schedule", "21-Apr-2025 for 200 days",
     "https://www.thehindu.com/business/Industry/govt-imposes-12-pc-safeguard-duty-on-certain-steel-products-for-200-days/article69476966.ece",
     "Partially verified - notification terms corroborated by The Hindu, Indian Express and ETInfra",
     "03-Aug-2026",
     "Covered hot-rolled coils, sheets and plates among five categories of non-alloy and alloy flat products."),

    ("S30", 3, "Aggregator of exchange filings", "screener.in",
     "Company pages - consolidated Profit & Loss, Balance Sheet and Quarterly Results",
     "Accessed 03-Aug-2026", "Sections 'profit-loss', 'balance-sheet', 'quarters'",
     "FY2015-FY2026 as available per company",
     "https://www.screener.in/",
     "Cross-checked - every FY2026 figure relied upon was reconciled to a Tier 1 or Tier 2 source, or to the sum of the four reported quarters",
     "03-Aug-2026",
     "Used only to build a consistent multi-year backbone and to cross-check. 'Operating Profit' here EXCLUDES other income and is the Standardised EBITDA basis."),

    ("S31", 2, "Press report of exchange filing / issuer investor update",
     "ET Manufacturing (Economic Times) and issuer investor update",
     "Shyam Metalics FY2026 results coverage and investor update",
     "11-May-2026 (board meeting and results); investor update May-2026",
     "Results summary", "Q4FY2026, FY2026, FY2025",
     "https://manufacturing.economictimes.indiatimes.com/news/industry/shyam-metalics-logs-45-8-jump-in-q4-net-profit-to-319-09-crore/131089712",
     "Cross-checked - company-reported EBITDA Rs 2,537 cr reconciles exactly to Standardised EBITDA Rs 2,333 cr plus other income Rs 204 cr per S30",
     "03-Aug-2026",
     "Statutory auditor MSKA & Associates LLP issued an unmodified opinion for FY2026."),

    ("S32", 1, "Subordinate legislation / executive order",
     "Ministry of Steel and Bureau of Indian Standards, Government of India",
     "Steel and Steel Products (Quality Control) Order, 2024 and subsequent amendments and suspensions",
     "QCO 2024; exemption extension ~20-Nov-2025; BIS amendments Feb-2026; stainless steel QCO suspension order dated 27-Apr-2026",
     "Amendment schedules", "In force during FY2026-FY2027",
     "https://www.bis.gov.in/wp-content/uploads/2026/02/Amendments-in-Quality-Control-Order.pdf",
     "Partially verified - BIS amendment document located; the 27-Apr-2026 stainless suspension order is evidenced by The Hindu and Economic Times reporting and corroborated by issuer commentary in S12",
     "03-Aug-2026",
     "The stainless-steel QCO suspension is a live FY2027 policy risk flagged by domestic producers."),

    ("S33", 1, "Subordinate legislation / press release",
     "Ministry of Commerce & Industry, Government of India",
     "Transition Facilitation (Quality Control) Order, 2026 and accompanying press release",
     "25-Jun-2026", "Press release", "Five-year transition window from 2026",
     "https://www.thehindu.com/business/Industry/union-government-eases-quality-control-order-rules-for-several-sectors-for-five-years/article71149440.ece",
     "Partially verified - press release content reported by The Hindu and Livemint",
     "03-Aug-2026",
     "Introduces an alternative risk-based, registration-based BIS compliance mechanism across several sectors."),

    ("S34", 1, "Issuer results release", "Vedanta Limited",
     "Q4 and FY26 Press Release", "29-Apr-2026", "Operational and financial highlights",
     "Q4FY2026, FY2026",
     "https://www.vedantalimited.com/public/uploads/19192/Vedanta-Q4-&-FY26---Press-Release.pdf",
     "Verified - full text retrieved and parsed", "03-Aug-2026",
     "Does NOT disclose a separate ESL Steel (Electrosteel) revenue, EBITDA or steel production line item. Vedanta demerger effective 01-May-2026."),

    ("S35", 1, "Issuer website", "ESL Steel Limited and Vedanta Limited",
     "Corporate website - steel business and plant descriptions", "Accessed 03-Aug-2026",
     "Business overview pages", "Current",
     "https://www.eslsteel.com/",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Greenfield integrated plant at Chandankyari, Bokaro district, Jharkhand; commissioned capacity 1.5 Mtpa."),

    ("S36", 1, "Insolvency order and exchange circulars",
     "National Company Law Tribunal (Mumbai) / IBBI and the stock exchanges",
     "Resolution plan approval order for Uttam Galva Steels Ltd; exchange suspension and delisting circulars",
     "NCLT order delivered 14-Oct-2022; trading suspended 17-Oct-2022; delisted 08-Dec-2022",
     "Order record and circulars", "FY2023 onwards",
     "https://ibbi.gov.in/uploads/order/7540d135638991b70df813ccdbc7536e.pdf",
     "Verified - IBBI order record and exchange circulars located; acquisition completion reported by ETInfra 11-Nov-2022",
     "03-Aug-2026",
     "Resolution applicant AM Mining India Pvt Ltd (ArcelorMittal group). Explains the absence of public financials from FY2023."),

    ("S37", 1, "Issuer investor presentation", "Tata Steel Limited",
     "Q1 FY27 results presentation", "31-Jul-2026", "Results summary and India expansion roadmap",
     "Q1FY2027 (Apr-Jun 2026)",
     "https://in.investing.com/news/company-news/tata-steel-q1-fy27-slides-india-strength-drives-40-mtpa-expansion-93CH-5526729",
     "Partially verified - headline figures via report of the issuer presentation; original deck not retrieved",
     "03-Aug-2026",
     "Q1FY2027 consolidated revenue Rs 60,794 cr, EBITDA Rs 9,370 cr (15.4% margin); India roadmap to 40 Mtpa."),

    ("S38", 1, "Issuer website", "Shyam Metalics and Energy Limited",
     "Corporate website - About Us / capacity disclosures", "Accessed 03-Aug-2026",
     "Installed metal capacity statements", "As at 31-Mar-2024 and 31-Dec-2024",
     "https://www.shyammetalics.com/about-us/",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "IMPORTANT: 'aggregate installed metal capacity' spans intermediate AND final products and therefore double-counts within the value chain. It is NOT crude steel capacity."),

    ("S39", 2, "Press report", "The Hindu",
     "Shyam Metalics plans $1.1 billion expansion", "Jun-2026", "Article text",
     "FY2027-FY2031 plan",
     "https://www.thehindu.com/business/shyam-metalics-plans-11-billion-expansion/article71123482.ece",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Plan to scale aggregate capacity to ~27 Mtpa by FY2031."),

    ("S40", 2, "Press report of policy impact", "ETInfra (Economic Times)",
     "Domestic steel prices surge 18-25% on extended safeguard duty", "Mar-2026", "Article text",
     "Q4FY2026 vs Q3FY2026",
     "https://infra.economictimes.indiatimes.com/news/construction/domestic-steel-prices-surge-18-25-on-extended-safeguard-duty/129674389",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "HRC Rs 55,900/t vs Rs 47,317/t in the December quarter; primary rebar Rs 59,800/t vs Rs 47,615/t."),

    ("S41", 2, "Press report of exchange filing", "Livemint / Business Standard / Reuters",
     "Jindal Steel FY2026 and Q1FY2027 results coverage",
     "01-May-2026 (FY26); 24-Jul-2026 (Q1FY27)", "Article text",
     "FY2026; Q1FY2027",
     "https://www.livemint.com/companies/news/jindal-steel-fy26-profit-earning-margins-11777648890744.html",
     "Cross-checked - Q4FY2026 revenue from operations of Rs 16,217.93 cr per Business Standard ties to the Mar-2026 quarter in S30",
     "03-Aug-2026",
     "Used to evidence Conflict C02 on the Jindal Steel FY2026 revenue basis."),

    ("S42", 2, "Press report", "The Hindu / Economic Times",
     "Stainless steel sector MSMEs flag import surge, urge Government to reintroduce quality control order",
     "Jun-Jul 2026", "Article text", "FY2027 to date",
     "https://www.thehindu.com/business/stainless-steel-sector-msmes-flag-import-surge-urges-govt-to-reintroduce-quality-control-order/article71146872.ece",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Establishes the 27-Apr-2026 order date for the stainless-steel QCO suspension."),

    ("S43", 2, "Press report", "Livemint",
     "Regulatory cloud lifts, Vedanta readies Bokaro capacity doubling", "Jan-2026", "Article text",
     "CY2026 target",
     "https://www.livemint.com/companies/vedanta-iron-steel-vedanta-anil-agarwal-bokaro-steel-plant-steel-capacity-expansion-esl-steel-bokaro-11782919317947.html",
     "Single-source secondary - treat as indicative", "03-Aug-2026",
     "ESL Bokaro steelmaking capacity targeted to double to 3.0 Mtpa by end-CY2026."),

    ("S44", 2, "Press report", "Economic Times",
     "Speciality steel PLI 1.2 investment commitments", "09-Feb-2026", "Article text",
     "PLI 1.2 round",
     "https://m.economictimes.indiatimes.com/industry/indl-goods/svs/steel/speciality-steel-pli-1-2-gets-rs-13000-crore-investment-commitments/articleshow/128113589.cms",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Rs 11,887 cr of investment commitments; 8.7 Mt of specialty steel capacity expected by FY2031."),

    ("S45", 2, "Press report", "Economic Times / ETEnergyworld",
     "Government launches PLI Scheme 1.1 for specialty steel", "06-Jan-2025", "Article text",
     "PLI 1.1 scheme design",
     "https://energy.economictimes.indiatimes.com/news/coal/govt-launches-pli-scheme-1-1-for-specialty-steel-to-boost-domestic-production/117008388",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Rs 6,322 cr allocation retained; five product categories; production period FY2026-FY2030."),

    ("S46", 2, "Press report / official taxonomy coverage",
     "S&P Global Commodity Insights and Economic Times",
     "India green steel taxonomy classification criteria and star rating", "13-20 Dec-2024",
     "Article text", "Taxonomy notified 23-Dec-2024",
     "https://www.spglobal.com/energy/en/news-research/latest-news/metals/121324-india-unveils-classification-criteria-for-green-steel",
     "Verified - retrieved via search snippet; notification date independently confirmed by S25",
     "03-Aug-2026",
     "Star-rating bands and the 2.2 tCO2e/tfs threshold. The 37% government-procurement share is a PROPOSAL, not an enacted mandate."),

    ("S47", 2, "Press report", "Economic Times / ETInfra",
     "SAIL capacity expansion roadmap to ~35 Mt by 2030-31", "Jul-Sep 2025", "Article text",
     "FY2031 target",
     "https://infra.economictimes.indiatimes.com/news/construction/sail-plans-to-expand-steel-production-to-35-million-tonnes-by-2030-31/123937485",
     "Verified - retrieved via search snippet", "03-Aug-2026",
     "Roughly Rs 1 lakh crore indicated outlay. Board-approved tranches are in S26; the 35 Mt figure is a stated ambition."),
]


# --------------------------------------------------------------------------------------
# Data dictionary: one row per (sheet, column). Satisfies "explain why every column exists".
# --------------------------------------------------------------------------------------
DICTIONARY_HEADERS = [
    "Sheet", "Column", "Definition", "Unit / Format", "Why this column exists",
]

DICTIONARY = [
    # --- Global conventions
    ("ALL SHEETS", "Source ID",
     "Key into the Sources sheet identifying the single document a figure was taken from.",
     "Text (Snn)",
     "Makes every number traceable to one document. Without it the workbook cannot be audited or refreshed."),
    ("ALL SHEETS", "Confidence",
     "High / Medium / Low assessment of how much reliance the figure can bear.",
     "Text",
     "Lets a modeller decide what to hard-code versus flex. High = primary issuer or government document read directly."),
    ("ALL SHEETS", "Reporting Basis",
     "Consolidated, Standalone, 100% basis (JV), Proforma India, or Industry aggregate.",
     "Text",
     "Mixing consolidated and standalone figures is the most common error in Indian steel comps. Stating basis on every row prevents it."),
    ("ALL SHEETS", "Currency", "Currency of the reported figure.", "Text (INR/USD/EUR/GBP)",
     "The peer set reports in four currencies. Silent currency mixing would corrupt any comparable table."),
    ("ALL SHEETS", "Unit", "Unit of measure of the value.", "Text",
     "Drives the number format applied and prevents Mt / kt / '000 t confusion."),
    ("ALL SHEETS", "Fiscal Year", "Indian fiscal year label; FY2026 = 1 Apr 2025 to 31 Mar 2026.",
     "Text (FYxxxx)",
     "Indian fiscal years are offset from calendar years. Several sources here are calendar-based and must be distinguishable."),
    ("ALL SHEETS", "Period Type", "Annual (FY), Calendar Year, Quarter, Month, or Point-in-time.",
     "Text",
     "Prevents a calendar-year worldsteel figure being compared with a fiscal-year JPC figure."),
    ("ALL SHEETS", "Last Updated", "Date this row was last written or reviewed.", "DD-MMM-YYYY",
     "Supports the quarterly update cycle and tells a reader how stale a row is."),
    ("ALL SHEETS", "Notes", "Row-specific caveats, definitional detail and cross-references.",
     "Text", "Carries the exceptions that would otherwise be lost when the sheet is copied into a model."),
    ("ALL SHEETS", '"Data Not Publicly Available" sentinel',
     "Text written into a cell, including numeric columns, where a figure is genuinely not in the "
     "public domain at the data cutoff.", "Text",
     "Distinguishes a gap that was investigated and found to be undisclosed from a gap that was "
     "overlooked - a blank cell cannot convey that. Consequence: some fiscal-year columns are "
     "mixed-type. This is safe in Excel because SUM and AVERAGE ignore text and every calculated "
     "column in this workbook is ISNUMBER-guarded inside IFERROR. In Power Query, replace the "
     "sentinel with null BEFORE setting the column type to decimal; do not force the type."),
    ("ALL SHEETS", "Methodology",
     "How the figure was arrived at: As reported, Derived, Computed, or Cross-checked.",
     "Text",
     "Distinguishes a number lifted from a filing from one this workbook calculated. Derived figures need re-derivation when data is restated."),

    # --- Company List
    ("Company List", "Coverage Tier", "Core Coverage or Supporting Coverage.", "Text",
     "Core names carry full financial build-out; supporting names are included for market structure and read-across."),
    ("Company List", "Listing Status", "Listed / Unlisted / Delisted, with the delisting route.", "Text",
     "Determines what disclosure exists. Delisted and unlisted names cannot be held to the same data standard."),
    ("Company List", "Primary Steelmaking Route", "BF-BOF, DRI-EAF, EAF, EOF or non-steelmaking converter.",
     "Text",
     "Route drives the cost curve, the coking-coal versus scrap/gas exposure, and the carbon intensity - the three biggest valuation drivers in this sector."),
    ("Company List", "Consolidation Basis Used",
     "The basis this workbook uses for the company's financial rows.", "Text",
     "Stated once per company so the Revenue, EBITDA and EBITDA/t sheets are internally consistent."),
    ("Company List", "Latest Reported Period",
     "Most recent period for which the company had reported at the data cutoff.", "Text",
     "Makes explicit where FY2026 was unavailable and an earlier period is the latest, as the brief requires."),

    # --- Production Capacity
    ("Production Capacity", "Crude Steel Capacity", "Nameplate or operating crude steel capacity.",
     "Mtpa", "The denominator for utilisation and the anchor for growth-capex modelling."),
    ("Production Capacity", "Capacity Definition",
     "Whether the figure is crude steel, liquid steel, hot metal, melt capacity or aggregate installed metal capacity.",
     "Text",
     "Companies publish different capacity constructs. Shyam Metalics' 'aggregate installed metal capacity' double-counts intermediates and is not crude steel."),
    ("Production Capacity", "Growth Pipeline", "Announced or Board-approved additional capacity.",
     "Mtpa", "Separates in-place earnings capacity from optionality that still needs capital and time."),
    ("Production Capacity", "Approval Status",
     "Commissioned, Under implementation, Board approved, or Announced/aspirational.", "Text",
     "An announced 40 Mtpa ambition and a Board-approved 4.08 Mtpa tranche are not the same asset and must not be summed."),

    # --- Production Volume
    ("Production Volume", "Crude Steel Production", "Crude steel produced in the period.", "Mt / mn t",
     "The volume line in any revenue build and the basis for JPC market-share analysis."),
    ("Production Volume", "Sales / Deliveries Volume", "Saleable steel sold or delivered in the period.",
     "Mt / mn t",
     "Revenue and EBITDA per tonne must be struck on the volume the company itself uses as the denominator; production and sales differ by inventory movement."),
    ("Production Volume", "Capacity Utilisation", "Production divided by capacity for the period.", "%",
     "The single best short-cycle operating indicator and the bridge between the Capacity and Volume sheets."),

    # --- Revenue
    ("Revenue", "Revenue from Operations",
     "Statutory revenue from operations, net of GST, per the audited or filed statement.",
     "Rs crore", "The only revenue construct that is comparable across the peer set."),
    ("Revenue", "Company-Headline Revenue",
     "The revenue figure the company leads with in investor material, where it differs from statutory revenue.",
     "Rs crore",
     "Jindal Steel headlines 'Gross Revenue' including GST and other income. Carrying both prevents an analyst reconciling to the wrong number."),

    # --- EBITDA
    ("EBITDA", "EBITDA - As Reported",
     "EBITDA on the company's own definition, taken from its results release or presentation.",
     "Rs crore / US$ m",
     "This is what the market quotes and what guidance is given against, so it must be present."),
    ("EBITDA", "EBITDA - Standardised",
     "Revenue from operations less operating expenses; EXCLUDES other income, finance cost, depreciation and amortisation, exceptional items and share of profit of JVs.",
     "Rs crore",
     "The peer set does not define EBITDA consistently - Shyam Metalics includes other income, Jindal Stainless does not. A single standardised basis is required before any multiple is calculated."),
    ("EBITDA", "Other Income Included in Reported EBITDA?",
     "Yes / No / Partly, evidencing the reconciliation between the two EBITDA columns.", "Text",
     "Turns an unexplained variance into a documented definitional difference."),

    # --- EBITDA per Ton
    ("EBITDA per Ton", "EBITDA per Tonne", "EBITDA divided by the relevant volume denominator.",
     "Rs/t or US$/t",
     "The sector's primary cross-cycle profitability metric, independent of scale and of currency where struck in USD."),
    ("EBITDA per Ton", "Volume Denominator",
     "Which volume was used: crude steel production, deliveries, or shipments.", "Text",
     "EBITDA/t moves several hundred rupees depending on the denominator. Tata Steel strikes it on deliveries; JSW on saleable sales. Not stating it makes the metric meaningless."),

    # --- Price sheets
    ("Steel Prices", "Assessment Basis",
     "Ex-works, ex-Mumbai trade, CFR, FOB; GST-inclusive or exclusive; month-end or period average.",
     "Text",
     "Indian HRC quotes differ by up to Rs 4,000/t purely on basis. The basis is as important as the number."),
    ("Iron Ore Prices", "Grade / Specification", "Fe content and size fraction.", "Text",
     "62% Fe fines, 65.5% Fe lump and pellet are different products with different prices and different netbacks."),
    ("Coking Coal Prices", "Benchmark / Assessment",
     "The specific coking coal assessment, including grade and delivery term.", "Text",
     "'Coking coal FOB Australia' is not one price. The Ministry of Steel and broker series differ by up to US$40/t - see Conflict C01."),

    # --- Demand, Trade, KPIs
    ("Demand & Consumption", "Apparent Finished Steel Consumption",
     "Production plus imports, less exports, adjusted for the change in stocks.", "Mt",
     "The demand measure JPC publishes and the one the Ministry quotes; it is an apparent, not end-use, measure."),
    ("Demand & Consumption", "Per Capita Consumption", "Finished steel consumption per head of population.",
     "kg", "The standard cross-country intensity comparator and the core of the long-run India demand thesis."),
    ("Imports & Exports", "Net Trade", "Exports less imports of total finished steel.", "Mt",
     "Determines whether domestic prices trade at import parity or export parity, which drives the whole domestic price deck."),
    ("Industry KPIs", "KPI", "The indicator name.", "Text",
     "A single dashboard-ready sheet so downstream tools bind to one place rather than scraping every sheet."),
]


# --------------------------------------------------------------------------------------
# Conflicts log
# --------------------------------------------------------------------------------------
CONFLICT_HEADERS = [
    "Conflict ID", "Topic", "Affected Sheet(s)", "Figure A (value and source)",
    "Figure B (value and source)", "Figure C (value and source)",
    "Why the figures differ", "Resolution adopted in this workbook", "Figure carried forward",
    "Residual risk",
]

CONFLICTS = [
    ("C01", "Coking coal benchmark level, FOB Australia",
     "Coking Coal Prices",
     "~US$225/t for Mar-2026 and ~US$246/t for Feb-2026 - Ministry of Steel, 'HCC Coking Coal f.o.b. Australia' [S01]",
     "US$186/t for Mar-2026, flat MoM after a 13% MoM fall in Feb-2026 - IDBI Capital [S20]",
     "US$200/t at 22-Jun-2026 with a 52-week range of US$135-217/t - IDBI Capital [S21]",
     "'Coking coal FOB Australia' is not a single price. Differences arise from grade (Premium Low-Vol Hard Coking Coal versus mid-vol, PCI or semi-soft), index provider and methodology (Platts, Argus, Fastmarkets, IHS), delivery term (FOB Australia versus CFR India) and assessment convention (spot versus monthly average versus quarterly settlement). Decisively, IDBI's 52-week HIGH of US$217/t as at Jun-2026 sits BELOW the Ministry's Feb-2026 level of US$246/t, so the two cannot be the same assessment.",
     "Carry both series as separately labelled rows. Do not blend them and do not compute a single fiscal-year average across them. For modelling the cost base of Indian integrated mills, prefer the Ministry of Steel / JPC assessment because it is the Government's own published benchmark for this industry and the series the Ministry itself uses in monthly reporting.",
     "Ministry of Steel / JPC assessment as the primary series; IDBI Capital retained as a labelled cross-check",
     "Neither series is available to this workbook as a complete monthly history, so fiscal-year averages for coking coal are NOT asserted. Obtain a licensed PRA series (Platts PLV HCC FOB Australia) before using coking coal in a formal cost model."),

    ("C02", "Jindal Steel FY2026 revenue basis",
     "Revenue; Company List",
     "Rs 53,225 crore - consolidated revenue from operations; equals the sum of the four FY2026 reported quarters (12,294 + 11,686 + 13,027 + 16,218) [S30], with the Mar-2026 quarter of Rs 16,217.93 cr independently confirmed by press reports of the filing [S41]",
     "Rs 62,412 crore - 'Gross Revenue' as headlined by the company, expressly stated to INCLUDE GST and other income [S11]",
     "Rs 53,553 crore [S41 - Livemint] and Rs 54,320 crore [Economic Times yearly table], on wider bases",
     "The company's investor material leads with a gross measure that includes indirect tax and non-operating income. Press and database figures sit between the two because some add other income to revenue from operations, and some report total income. Only revenue from operations net of GST is comparable to the rest of the peer set.",
     "Use Rs 53,225 crore as the comparable statutory revenue from operations, verified by quarterly summation and by an independent tie to the Mar-2026 quarter. Additionally carry the Rs 62,412 crore company headline in a separate, clearly labelled column so that a reader reconciling to the company's own deck is not misled.",
     "Rs 53,225 crore (statutory, comparable); Rs 62,412 crore shown separately as the company headline",
     "The FY2025 comparative is less clean: the audited annual column is Rs 50,129 cr whereas the four FY2025 quarters sum to Rs 49,765 cr, a Rs 364 cr difference consistent with a fourth-quarter reclassification. FY2025 growth rates should therefore be quoted with the basis stated."),

    ("C03", "India FY2026 finished steel production and consumption - data vintage",
     "Demand & Consumption; Production Volume; Industry KPIs",
     "Finished steel production 160.94 Mt; consumption 163.74 Mt - Ministry of Steel Monthly Economic Report for March 2026, Annexure-I, citing JPC (April-2026 vintage) [S01]",
     "Total finished steel production 161.74 Mt; consumption 164.19 Mt - Ministry of Steel 'Development of Indian Steel Sector since 2014-15' (June-2026 vintage), citing JPC [S02]",
     "",
     "JPC provisional data is revised as returns are received under the Collection of Statistics Act, 2008. The June-2026 document is the later vintage and also labels its series explicitly as 'Total Finished Steel (alloy/stainless + non-alloy)'. Both documents are the same publisher citing the same compiler, at two points in the revision cycle.",
     "Use the LATER (June-2026) vintage for the long-run FY2015-FY2026 series on the Demand & Consumption sheet. Retain the April-2026 vintage for the supply-balance table (production + imports - exports - stock change = consumption) because that table is internally consistent and self-reconciling. Both vintages are shown, each labelled with its source and vintage.",
     "Both retained, each labelled. Long-run series uses the June-2026 vintage.",
     "A third revision is likely before the figures are declared final. Any model built on FY2026 India volumes should be refreshed against the then-current JPC vintage at each quarterly update."),

    ("C04", "India crude steel capacity, FY2026",
     "Production Capacity; Industry KPIs",
     "220.4 Mt - Ministry of Steel, An Overview of Steel Sector, June-2026 [S03]; the same figure appears in the June-2026 Development document [S02]",
     "220.3 Mt - Ministry of Steel, An Overview of Steel Sector, March-2026 [S04]",
     "",
     "Successive vintages of the same monthly Ministry publication, reflecting the JPC revision cycle. The difference is 0.1 Mt, or under 0.05%.",
     "Adopt the later vintage, 220.4 Mt, and disclose the earlier figure.",
     "220.4 Mt",
     "Immaterial for modelling. Noted only for completeness and to demonstrate that vintages were checked rather than assumed identical."),

    ("C05", "India per capita finished steel consumption, FY2026",
     "Demand & Consumption; Industry KPIs",
     "115.7 kg - Ministry of Steel, An Overview of Steel Sector, June-2026, citing JPC [S03]",
     "115 kg - Ministry of Steel, An Overview of Steel Sector, March-2026, citing JPC [S04]",
     "",
     "Later vintage plus a rounding convention difference; the March document rounds to a whole number.",
     "Adopt the later, more precise figure of 115.7 kg.",
     "115.7 kg",
     "None material."),

    ("C06", "India crude steel output - fiscal versus calendar year",
     "Production Volume; Industry KPIs",
     "168.42 Mt for FY2026 (Apr-2025 to Mar-2026) - JPC via Ministry of Steel [S01]",
     "164.89 Mt for CY2025 - World Steel Association, provisional [S07]",
     "",
     "This is NOT a data conflict. The two figures cover different twelve-month periods and are compiled by different agencies on different definitions. They are frequently, and incorrectly, quoted interchangeably.",
     "Carry both, each labelled with its period type and compiler. The Period Type column on every row prevents the two being mixed. Fiscal-year figures are used for all India-specific analysis; the worldsteel calendar series is used only for cross-country comparison.",
     "Both, explicitly labelled",
     "Low, provided the Period Type column is respected. This is flagged because conflating the two is a common and material error in sector notes."),

    ("C07", "Indian HRC price level, March 2026",
     "Steel Prices",
     "Rs 57,700/MT at end-March 2026, up ~14% QoQ - ICRA [S19]",
     "Rs 59,500/t for Mar-2026, up 10.2% MoM and a 45-month high - IDBI Capital [S20]",
     "Rs 55,900/t versus Rs 47,317/t in the December quarter - ETInfra [S40]",
     "Differing assessment point (month-end versus monthly average), location and basis (ex-works versus ex-Mumbai trade), GST treatment, grade and thickness, and primary-mill versus secondary or trade quotes.",
     "Carry all three, each labelled with provider and basis. For modelling, prefer ICRA's end-March Rs 57,700/MT because ICRA states the assessment point and the quarter-on-quarter construction, making the figure reproducible. Note that none of these are GST-inclusive retail prices and none is directly comparable to the Ministry's Mumbai retail series.",
     "ICRA Rs 57,700/MT (end-March 2026) as the reference; the other two retained as labelled alternatives",
     "Without a licensed PRA series the fiscal-year average HRC realisation cannot be constructed from these point observations. Company-disclosed EBITDA/t remains the more reliable profitability input."),

    ("C08", "Safeguard duty - continuous levy or reinstatement",
     "Government Policies; Steel Prices",
     "Continuous: the definitive notification of 30-Dec-2025 sets year 1 as 21-Apr-2025 to 20-Apr-2026, implying no gap [S27]",
     "Reinstatement: contemporaneous coverage and ICRA describe a lapse and a subsequent reinstatement from January 2026, with HRC falling to Rs 46,000/MT in early December 2025 and rebounding thereafter [S19]",
     "",
     "Both are correct in different senses. The PROVISIONAL measure of 21-Apr-2025 was imposed for 200 days and lapsed on expiry around 07-Nov-2025. The DEFINITIVE measure was notified on 30-Dec-2025 with a year-1 period dated from 21-Apr-2025, so the levy appears continuous on the face of the notification while there was an effective interruption in the intervening weeks.",
     "Present the dated chronology rather than a single characterisation, and note that the observed market behaviour - HRC to Rs 46,000/MT in early December 2025, then a rebound from January 2026 - is consistent with an effective gap in the levy.",
     "Full chronology on the Government Policies sheet",
     "The mid-term review provided for in the notification could change the year-2 rate of 11.5% currently in force from 21-Apr-2026. Monitor DGTR and Ministry of Finance releases."),

    ("C09", "SAIL FY2025 turnover and EBITDA basis",
     "Revenue; EBITDA",
     "Revenue from operations Rs 1,02,479 cr (consolidated) and Rs 1,02,478 cr (standalone) for FY2025 [S10]",
     "Annual turnover Rs 1,01,716 cr and EBITDA Rs 11,764 cr for FY2025 - Ministry of Steel [S26]",
     "",
     "The Ministry quotes a turnover measure Rs 763 cr below revenue from operations, consistent with net sales excluding other operating revenue. The EBITDA of Rs 11,764 cr matches SAIL's own STANDALONE press-release EBITDA for FY2025 exactly, confirming the Ministry is quoting SAIL on a standalone basis. Separately, three different SAIL FY2026 EBITDA figures all reconcile once the basis is fixed: Rs 13,146 cr is the company's STANDALONE headline; Rs 12,894 cr is consolidated EBITDA INCLUDING other income (profit before exceptionals, JV share and tax of Rs 4,748 cr, plus finance cost Rs 2,158 cr, plus depreciation Rs 5,988 cr); and Rs 12,000 cr is consolidated EBITDA EXCLUDING other income (Rs 12,894 cr less other income of Rs 894 cr).",
     "Use SAIL's own audited filing for all financial rows. Treat the Ministry figures as corroboration of the standalone basis rather than as an alternative measurement, and state on the EBITDA sheet that SAIL's headline EBITDA is standalone while its revenue and profit rows here are consolidated. Apply the workbook's standard definition - EBITDA excluding other income - for the Standardised column, giving Rs 12,000 cr for FY2026.",
     "SAIL audited filing [S10]. FY2026: Rs 13,146 cr as the company-reported standalone headline; Rs 12,000 cr as Standardised consolidated EBITDA excluding other income; Rs 12,894 cr disclosed in Notes as the consolidated figure including other income",
     "Users building EV/EBITDA for SAIL must not pair a consolidated enterprise value with the standalone EBITDA headline."),

    ("C10", "Shyam Metalics FY2026 EBITDA definition",
     "EBITDA; EBITDA per Ton",
     "Rs 2,537 crore - company-reported EBITDA, +21% YoY [S31]",
     "Rs 2,333 crore - revenue from operations less operating expenses, excluding other income [S30]",
     "",
     "Not a conflict but a definitional difference, and it reconciles exactly: Rs 2,333 cr plus FY2026 other income of Rs 204 cr equals Rs 2,537 cr. Shyam Metalics includes other income in its reported EBITDA; Jindal Stainless does not, whose reported Rs 5,560 cr sits within Rs 1 cr of its standardised Rs 5,561 cr.",
     "Carry both figures in the two EBITDA columns and record 'Yes' in the 'Other Income Included in Reported EBITDA?' column for Shyam Metalics and 'No' for Jindal Stainless. Use the standardised column for any cross-company multiple.",
     "Both, in their respective labelled columns",
     "Low. This is precisely why the EBITDA sheet carries two columns rather than one."),

    ("C11", "Mukand Ltd FY2026 profit versus operating profit",
     "EBITDA; Revenue",
     "Standardised EBITDA Rs 172 cr for FY2026 [S30]",
     "Profit before tax Rs 512 cr and net profit Rs 604 cr for FY2026 [S30]",
     "",
     "Net profit exceeds standardised EBITDA by a wide margin, which can only be explained by a material non-operating gain, an exceptional item, a share of profit of associates or joint ventures, or a deferred-tax write-back. The composition cannot be established without reading the audited filing, which was not retrieved within the research window.",
     "Report the figures as sourced, mark Confidence as Medium, and flag explicitly that Mukand's FY2026 profit is not operating in nature. Do not use Mukand FY2026 PAT in any operating comparison or margin analysis until the filing is read.",
     "Figures as sourced, with an explicit non-operating flag",
     "Material for anyone screening on Mukand earnings. Resolve by reading the FY2026 audited results before use."),

    ("C12", "Kirloskar Ferrous FY2026 net profit exceeding profit before tax",
     "EBITDA",
     "Profit before tax Rs 497 cr for FY2026 [S30]",
     "Net profit Rs 507 cr for FY2026 [S30]",
     "",
     "Net profit above profit before tax indicates a net tax credit, most likely a deferred-tax write-back or the reversal of a prior-period provision. Internally plausible but unverified.",
     "Report as sourced with Confidence Medium and a flag. Use profit before tax for any normalised earnings work on this name.",
     "Figures as sourced, flagged",
     "Low in isolation but it distorts any FY2026 net-margin or effective-tax-rate screen that includes this company."),

    ("C13", "Gallantt FY2026 revenue - annual column versus quarterly sum",
     "Revenue",
     "Rs 4,419 crore - annual consolidated column [S30]",
     "Rs 4,438 crore - sum of the four FY2026 quarters [S30]",
     "",
     "A Rs 19 cr difference, about 0.4%, consistent with a fourth-quarter reclassification or a rounding convention in the aggregator. The same aggregator shows both, so this is an internal inconsistency in a Tier 3 source rather than a disagreement between publishers.",
     "Use the annual audited column of Rs 4,419 cr, mark Confidence Medium, and record that the quarterly sum differs. Verify against the company's filing before relying on Gallantt in a comparable table.",
     "Rs 4,419 crore (annual column)",
     "Immaterial at the sector level; verify before company-specific work. Note also that Gallantt Ispat and Gallantt Metal were amalgamated, so pre-merger periods are not like-for-like."),

    ("C14", "World Bank iron ore series - unit label",
     "Iron Ore Prices",
     "Column header in the Pink Sheet workbook reads '($/dmtu)' [S17]",
     "The Pink Sheet 'Description' sheet states at row 90 that iron ore spot is quoted 'in US dollar/dry ton', and at row 91 defines the series as 'Iron ore (any origin) fines, spot price, c.f.r. China, 62% Fe' [S17]",
     "",
     "The '$/dmtu' header is a legacy label retained from the era of annual contract pricing quoted in US cents per dry metric tonne unit. The current spot series is in US dollars per dry metric tonne. Taking the header at face value would misstate iron ore by a factor of roughly 62.",
     "Label the series in this workbook as US$/dmt for 62% Fe fines CFR China, cite the World Bank Description sheet as the authority for the unit, and record the legacy header so a reader comparing against the raw Pink Sheet is not confused.",
     "US$/dmt, 62% Fe fines, CFR China",
     "None, once documented. Flagged because it is a classic and expensive units error."),

    ("C15", "World Bank Australian coal series - thermal, not coking",
     "Coking Coal Prices",
     "Series name is 'Coal, Australian' and is frequently used as a coal cost proxy [S17]",
     "The Pink Sheet 'Description' sheet, row 4, defines it as 'Coal (Australia), from February 2022, port THERMAL, f.o.b. Newcastle, 6000 kcal/kg futures price' [S17]",
     "",
     "The series is thermal coal, priced off energy content, and has no consistent relationship with metallurgical coking coal, which is priced off coking properties. Using it as a coking coal proxy would have understated FY2026 coking coal costs by roughly half.",
     "Include the series only as an energy and captive-power cost reference, labelled THERMAL in the row description, physically separated from the coking coal rows, and excluded from any coking coal average.",
     "Retained as a clearly labelled thermal energy reference only",
     "None, once labelled. Flagged because the naming invites exactly this misuse."),

    ("C16", "AM/NS India - fiscal year mismatch",
     "Revenue; EBITDA; EBITDA per Ton; Production Volume",
     "ArcelorMittal discloses AM/NS India on a 100% basis, in USD, for CALENDAR quarters and calendar years [S13][S14]",
     "Every other company in this universe reports on an Indian fiscal year ending 31 March, in Indian rupees",
     "",
     "AM/NS India is an unlisted 60:40 joint venture of ArcelorMittal and Nippon Steel and does not publish full Ind-AS consolidated statements publicly. Its only regular public disclosure is the summary table in ArcelorMittal's quarterly earnings releases, which is calendar-based and dollar-denominated.",
     "Carry the calendar-year figures exactly as disclosed, AND separately present a derived Apr-March fiscal-year equivalent built by summing the four relevant calendar quarters (2Q25 + 3Q25 + 4Q25 + 1Q26 for FY2026). Every derived row is marked Methodology = 'Derived - sum of calendar quarters' so it can never be mistaken for a company-reported fiscal-year figure.",
     "Calendar-year figures as reported, plus a clearly flagged derived FY2026 equivalent",
     "The derived fiscal-year figure is arithmetically sound but is not a company-reported number and has not been audited on that basis. A derived FY2025 equivalent is NOT presented because the 2Q24 and 3Q24 quarterly disclosures were not retrieved, so FY2025 growth for AM/NS India is deliberately left blank rather than estimated."),
]
